In [1]:
#Importing necessary libraries-
import selenium
import pandas as pd
import time
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException, InvalidElementStateException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import os
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
import chromedriver_autoinstaller

import warnings
warnings.filterwarnings('ignore')

In [2]:
driver=webdriver.Chrome()

In [3]:
driver.get('https://www.manyavar.com/')

In [4]:
#Searching for men's apparel
search=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[2]/div[2]/div[2]/div/div/div[12]/a/picture/img')
search.click()

In [6]:
#Searching for men's apparel
search1=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/section/div/div[2]/div/ul/li[5]')
search1.click()

In [5]:
# Fetching product URL first
product_url=[]
start=0
end=1

for page in range(start,end):
    urls=driver.find_elements(By.XPATH,'//div[@class="product-tile"]/div/div/a[1]')
    for url in urls:
        product_url.append(url.get_attribute('href'))
        print("Appended URL:", url.get_attribute('href'))
    print("Finished processing")

Appended URL: https://www.manyavar.com/en-in/kurta-pajama/rust-orange-printed-kurta-set/UC114639.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/flamingo-pink-chikankari-embroidered-kurta-set/UC113704.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/teal-blue-chikankari-patterned-kurta-set/UC113705.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/lime-green-chikankari-kurta-set/UC106513.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/quartz-pink-mandala-printed-kurta-set/UC117609.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/ivory-white-traditional-south-indian-kurta-pancha-set/UC107170.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/ruby-pink-harlequin-printed-kurta-set/UC114756.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/powder-blue-chikankari-embroidered-kurta-set/UC113541.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/candlelight-yellow-floral-patterned-sequined-chikankari-kurta-set/UC113539.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/feroze-blue-chikankari-kurta-set/UC108407.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/maroon-chikankari-kurta-set/UC108402.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/black-solid-minimalist-kurta-pajama/UC106450.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/maroon-georgette-kurta-set/UC100874.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/light-pink-and-cream-floral-embroidered-kurta-set/UC113687.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/feroze-kurta-pajama-with-golden-motif/UC106328.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/navy-blue-diamond-chikankari-patterned-kurta-set/UC106506.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/turkish-green-diamond-patterned-kurta-set/UC113769.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/carnation-pink-self-design-kurta-pajama/UC100880.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/tropical-blue-floral-chikankari-embroidered-kurta-set/UC108392.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/light-pink-sequins-kurta-pajama/UC100909.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/bright-cream-floral-chikankari-embroidered-kurta-set/UC117607.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/pristine-white-kurta-set-with-embroidered-placket-and-neckline/UC113753.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/black-patterned-kurta-set/UC120341.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/tropical-pink-botanical-printed-kurta-set/UC116313.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/forest-green-buti-printed-kurta-set/UC100934.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/teal-red-plain-kurta-set-with-embroidered-collar/UC113752.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/pista-green-and-beige-diamond-patterned-kurta-set/UC117617.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/melon-orange-floral-printed-kurta-set/UC120374.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/stone-grey-botanical-printed-kurta-set/UC116310.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/off-white-celebration-wear-self-design-kurta-pajama/UC106462.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/navy-blue-self-design-kurta-pajama/UC100886.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/royal-maroon-printed-kurta-set/UC100932.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/grey-kurta-pajama-with-golden-motif/UC106325.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/aspen-gold-yellow-chikankari-kurta-set/UC106511.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/rosewater-pink-vertical-striped-kurta-set/UC113757.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/primrose-yellow-chikankari-embroidered-kurta-set/UC120343.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/aquamarine-blue-watercolor-effect-printed-kurta-set/UC124238.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/berry-wine-patterned-kurta-set/UC113518.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/blissful-blue-and-copper-floral-medallion-patterned-kurta-set/UC113709.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/subtle-green-plain-kurta-set/UC113750.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/marble-blue-tree-of-life-print-kurta-set/UC117616.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/turquoise-blue-diamond-patterned-chikankari-embroidered-kurta-set/UC113538.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/sky-blue-festive-kurta-pajama/UC106471.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/pearl-river-grey-floral-patterned-kurta-set/UC113562.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/dark-brown-printed-kurta/UC107232.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/white-booti-self-motif-kurta-pajama/UC113631.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/maroon-printed-kurta-set/UC113592.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/sea-green-jacquard-kurta-pajama/UC106474.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/amber-yellow-kurta-set-with-floral-embroidered-neckline/UC116284.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/coral-pink-jaal-patterned-kurta-set/UC113773.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/sunrise-orange-floral-spot-patterned-kurta-set/UC113635.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/bottle-green-printed-kurta-pajama/UC114714.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/navy-blue-ogee-patterned-kurta-set/UC113543.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/light-pink-floral-patterned-kurta-set/UC113688.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/light-pink-striped-kurta-set/UC113776.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/sunrise-yellow-kurta-set-with-embroidered-placket/UC113719.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/sunrise-orange-floral-spot-patterned-kurta-set/UC106236.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/blue-plain-kurta-set/UC106423.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/indigo-blue-booti-work-kurta-pajama/UC117600.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/aquamarine-blue-sequined-kurta-set/UC117606.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/crayola-yellow-polka-dotted-kurta-set/UC113728.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/teal-green-kurta-set/UC113623.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/summer-green-embellished-kurta-set/UC106228.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/merlot-red-jacquard-kurta-set/UC106077.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/basic-cream-kurta-set/UC100837.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/black-self-embroidered-kurta-pajama/UC106507.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/salt-white-solid-kurta-set/UC102800.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/amber-yellow-self-design-kurta-set/UC104299.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/feroze-self-design-kurta-set/UC104360.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/pastel-pink-kurta-with-embroidery-work/UC106235.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/beige-jacquard-kurta-set/UC100831.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/pomegranate-red-jacquard-patterned-kurta-set/UC106324.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/indigo-blue-self-chequered-kurta/UC102796.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/wine-self-design-kurta-with-black-churidar/UC104252.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/pearl-white-solid-kurta-set/UC102870.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/classic-black-kurta/UC104357.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/mustard-yellow-plain-kurta-set-with-neck-detailing/UC104247.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/traditional-chikankari-blue-kurta-set/UC106258.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/dusty-rose-pink-jacquard-patterned-kurta-set/UC113625.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/light-green-solid-kurta-set/UC102797.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/deep-mahogany-brown-embellished-buttoned-kurta-set/UC113661.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/peacock-blue-jacquard-patterned-kurta-set/UC113534.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/ivory-white-plain-kurta-set/UC102728.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/seafoam-green-solid-kurta-set-with-neck-detailing/UC102760.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/off-white-plain-kurta-set/UC104338.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/aqua-green-chikankari-kurta-pajama/UC106436.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/indigo-blue-booti-work-kurta-set/UC106394.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/aquamarine-blue-chikankari-kurta-set/UC106512.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/sand-white-jacquard-patterned-kurta-set-/UC113556.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/merlot-red-jacquard-kurta-pajama/UC100897.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/light-green-jacquard-kurta-set/UC106276.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/wine-self-floral-motif-kurta-set/UC104332.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/black-solid-kurta-set/UC106339.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/shell-white-embellished-button-kurta-set/UC106410.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/scarlet-red-kurta-set-with-neck-detailing/UC100835.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/fern-green-jacquard-kurta-pajama/UC106472.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/brilliant-white-placket-detailed-kurta-set/UC117503.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/mint-green-chikankari-embroidered-kurta-set-/UC107204.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/black-self-design-kurta-pajama/UC106399.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/faded-green-printed-kurta-set/UC106333.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/cream-white-patterned-placket-kurta-set/UC113552.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/ruby-red-plain-kurta-set/UC102754.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/yellow-self-design-kurta-pajama/UC102850.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/pastel-green-self-design-kurta-set/UC106225.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/sage-green-self-checquered-kurta-pajama/UC106457.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/mauve-wine-dotted-patterned-kurta-set/UC113586.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/rust-pink-self-design-kurta-set/UC106195.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/rose-pink-self-motif-kurta-set/UC102793.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/off-white-contrast-placket-kurta-set/UC113551.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/daffodil-yellow-dotted-patterned-kurta-set/UC113639.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/mint-green-jacquard-kurta-set/UC100858.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/butterfly-green-jacquard-pattern-kurta-set/UC114620.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/squash-yellow-patterned-placket-kurta-set/UC117414.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/sunrise-orange-placket-detailed-kurta-set/UC117501.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/green-kurta-with-embroidered-collar/UC106488.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/candlelight-orange-placket-detailed-kurta-set/UC113680.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/candlelight-orange-placket-detailed-kurta-set/UC106490.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/dark-blue-chikankari-kurta/UC108409.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/bright-white-floral-chikankari-kurta-set/UC108410.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/black-chikankari-kurta-set/UC108404.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/jamun-purple-sequin-embellished-chikankari-kurta-set/UC117602.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/quartz-pink-floral-chikankari-embroidered-kurta-set/UC117604.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/teal-green-self-striped-kurta-set/UC122680.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/forest-green-chikankari-embroidered-sequined-kurta-set/UC122475.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/pastel-turquoise-blue-floral-chikankari-patterned-kurta-set/UC116342.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/midnight-blue-sequined-kurta-set/UC122474.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/powder-blue-sequin-embellished-chikankari-kurta-set/UC117603.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/forest-green-chikankari-embroidered-sequined-kurta-set/UC108405.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/sunglow-yellow-chikankari-embroidered-sequinned-kurta-set/UC124407.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/serenity-blue-chikankari-embroidered-kurta-set/UC106418.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/lime-yellow-chikankari-kurta-set/UC108406.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/ash-grey-chikankari-embroidered-sequinned-kurta-set/UC124406.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/ice-blue-ombre-effect-floral-lattice-printed-kurta-set/UC126762.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/star-white-chikankari-embroidered-sequinned-kurta-set/UC124405.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/jamun-purple-jaal-patterned-chikankari-kurta-set/UC120351.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/soft-green-botanical-printed-kurta-set/UC114645.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/amaranth-pink-chikankari-jaal-patterned-kurta-set/UC120352.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/dove-grey-chikankari-sequined-kurta-set/UC122343.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/lilac-purple-sequined-kurta-set/UC122646.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/light-beige-zari-bordered-traditional-south-indian-pancha-set/UC106808.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/melon-peach-and-cream-zari-detailed-traditional-south-indian-pancha-set/UC126329.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/pristine-white-self-striped-kurta-set/UC122677.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/mehendi-green-self-patterned-kurta-set/UC120400.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/bright-mustard-chikankari-sequinned-kurta-set/UC122481.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/biscuit-colour-plain-kurta-set/UC117288.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/lavender-medallion-printed-kurta-set/UC116344.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/soft-white-floral-sequin-embroidered-kurta-set/UC122476.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/golden-jacquard-printed-kurta-set/UC113739.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/antique-white-angrakha-style-diamond-printed-kurta-set/UC126766.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/soft-blue-medallion-print-kurta-set/UC122342.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/ivory-cream-detailed-traditional-south-indian-shirt-and-veshti-set/UC124468.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/maroon-self-patterned-kurta-set/UC122678.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/turquoise-blue-self-patterned-kurta-set/UC122681.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/jet-black-chikankari-sequinned-kurta-set/UC100876.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/jade-green-buta-patterned-kurta-set/UC106330.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/kohl-black-botanical-embroidered-kurta-set/UC113549.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/deep-maroon-chikankari-embroidered-sequinned-kurta-set/UC122817.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/soft-cream-bandhgala-neckline-kurta-set/UC124703.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/lemon-drop-yellow-chikankari-embroidered-kurta-set/UC106508.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/pristine-white-angrakha-kurta-set/UC126743.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/grey-self-motif-kurta-set/UC106358.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/deep-blue-floral-string-printed-kurta-set/UC126747.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/teal-green-ogee-patterned-kurta-set/UC125341.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/sea-green-sequin-embellished-chikankari-kurta-set/UC120340.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/forest-green-and-cream-zari-detailed-traditional-south-indian-dhoti-set/UC125816.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/teal-blue-self-patterned-kurta-set/UC122679.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/sage-green-angrakha-style-kurta-set/UC126731.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/maroon-wave-printed-kurta-set/UC126749.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/soft-white-floral-print-kurta-set/UC126776.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/sage-green-lattice-patterned-kurta-set/UC117615.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/aqua-blue-chikankari-embroidered-sequined-kurta-set/UC122648.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/canary-yellow-jaal-patterned-kurta-set/UC124257.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/pristine-white-chikankari-kurta-set/UC106504.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/sapphire-blue-bel-buti-printed-kurta-set/UC126727.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/teal-green-angrakha-kurta-set/UC126742.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/raspberry-pink-leaf-patterned-kurta-set/UC124851.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/cloud-grey-ombre-effect-floral-lattice-printed-kurta-set/UC126760.html
Appended URL: https://www.manyavar.com/en-in/kurta-pajama/biscuit-cream-shankh-patterned-kurta-set/UC100930.html

In [6]:
len(product_url)

203

In [32]:
#Extracting first few records for men
for url in product_url[0:30]:
    driver.get(url)
    time.sleep(2)
    

Brandname=[]
Category=[]
Producttype=[]
ProductName=[]
Productcode=[]
Price=[]
Weartype=[]
Materialtype=[]
Returntime=[]
reviews=[]
Countryoforigin=[]
reviews=[]
Occasion=[]
color1=[]
color2=[]
Size1=[]
Size2=[]
Size3=[]
Size4=[]

In [33]:
for url in product_url[0:30]:
    driver.get(url)
    time.sleep(2)
    
    
    try:
        Brand_name=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[6]/div[2]/p")
        Brandname.append(Brand_name.text)
    except NoSuchElementException:
        Brandname.append('--------')
   
    try:
        Cat=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/button/h3")
        Category.append(Cat.text)
    except NoSuchElementException:
        Category.append('--------')
        

    try:
        Product_type=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/ul/li[1]/a")
        Producttype.append(Product_type.text)
    except NoSuchElementException:
        Producttype.append('--------')
        
    try:
        Product_Name=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[1]/div/h1")
        ProductName.append(Product_Name.text)
    except NoSuchElementException:
        ProductName.append("--------")
        
    try:
        Product_code=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[3]/div/span")
        Productcode.append(Product_code.text)
    except NoSuchElementException:
        Productcode.append("--------")
        
    try:
        Price_u=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[2]/div/div/div/span/span/span/h2")
        Price.append(Price_u.text)
    except NoSuchElementException:
        Price.append("--------")

In [34]:
len(Brandname), len(Category), len(Producttype), len(ProductName), len(Productcode), len(Price)

(30, 30, 30, 30, 30, 30)

In [44]:
data = {
    'Brand': Brandname,
    'Category': Category,
    'Product_type': Producttype,
    'Product_Name': ProductName,
    'Product_code': Productcode,
    'Price': Price
    }

In [45]:
df = pd.DataFrame(data)

In [47]:
df.rename_axis('Sno',inplace=True)

In [51]:
df

,Brand,Category,Product_type,Product_Name,Product_code,Price
Sno,,,,,,
0,Vedant Fashions Ltd.,Men,Kurta Pajama,Rust Orange Printed Kurta Set,SOSK630-332,"₹ 3,499"
1,Vedant Fashions Ltd.,Men,Kurta Pajama,Flamingo Pink Chikankari Embroidered Kurta Set,SDES820-325,"₹ 4,999"
2,Vedant Fashions Ltd.,Men,Kurta Pajama,Teal Blue Chikankari Patterned Kurta Set,SDES820-326,"₹ 4,999"
3,Vedant Fashions Ltd.,Men,Kurta Pajama,Lime Green Chikankari Kurta Set,SDES784-334,"₹ 3,999"
4,Vedant Fashions Ltd.,Men,Kurta Pajama,Quartz Pink Mandala Printed Kurta Set,CPOSK666-325,"₹ 4,999"
5,Vedant Fashions Ltd.,Men,Kurta Pajama,Ivory White Traditional South Indian Kurta Pan...,SOSK579-340,"₹ 16,999"
6,Vedant Fashions Ltd.,Men,Kurta Pajama,Ruby Pink Harlequin Printed Kurta Set,SOSK695-325,"₹ 4,999"
7,Vedant Fashions Ltd.,Men,Kurta Pajama,Powder Blue Chikankari Embroidered Kurta Set,SDES626-341,"₹ 4,999"
8,Vedant Fashions Ltd.,Men,Kurta Pajama,Candlelight Yellow Floral Patterned Sequined C...,SDES626-328,"₹ 4,999"
9,Vedant Fashions Ltd.,Men,Kurta Pajama,Feroze Blue Chikankari Kurta Set,CPOSK612-326,"₹ 3,999"
10,Vedant Fashions Ltd.,Men,Kurta Pajama,Maroon Chikankari Kurta Set,CPOSK612-307,"₹ 3,999"
11,Vedant Fashions Ltd.,Men,Kurta Pajama,Black Solid Minimalist Kurta Pajama,SDES634-310,"₹ 3,999"
12,Vedant Fashions Ltd.,Men,Kurta Pajama,Maroon Georgette Kurta Set,CPOSK452-307,"₹ 5,999"
13,Vedant Fashions Ltd.,Men,Kurta Pajama,Light Pink and Cream Floral Embroidered Kurta Set,SDES806-301,"₹ 5,999"
14,Vedant Fashions Ltd.,Men,Kurta Pajama,Feroze Kurta Pajama With Golden Motif,SDES515-326,"₹ 3,999"
15,Vedant Fashions Ltd.,Men,Kurta Pajama,Navy Blue Diamond Chikankari Patterned Kurta Set,SDES784-306,"₹ 3,999"
16,Vedant Fashions Ltd.,Men,Kurta Pajama,Turkish Green Diamond Patterned Kurta Set,SDES869-333,"₹ 3,999"
17,Vedant Fashions Ltd.,Men,Kurta Pajama,Carnation Pink Self Design Kurta Pajama,CPOSK462-342,"₹ 2,999"
18,Vedant Fashions Ltd.,Men,Kurta Pajama,Tropical Blue Floral Chikankari Embroidered Ku...,CPOSK452-341,"₹ 5,999"
19,Vedant Fashions Ltd.,Men,Kurta Pajama,Light Pink Sequins Kurta Pajama,CPOSK563-319,"₹ 4,999"
20,Vedant Fashions Ltd.,Men,Kurta Pajama,Bright Cream Floral Chikankari Embroidered Kur...,CPOSK665-302,"₹ 5,999"
21,Vedant Fashions Ltd.,Men,Kurta Pajama,Pristine White Kurta Set with Embroidered Plac...,SDES857-301,"₹ 2,999"
22,Vedant Fashions Ltd.,Men,Kurta Pajama,Black Patterned Kurta Set,SDES632-310,"₹ 3,999"
23,Vedant Fashions Ltd.,Men,Kurta Pajama,Tropical Pink Botanical Printed Kurta Set,SOSK636-342,"₹ 3,499"
24,Vedant Fashions Ltd.,Men,Kurta Pajama,Forest Green Buti Printed Kurta Set,CPOSK607-316,"₹ 4,999"
25,Vedant Fashions Ltd.,Men,Kurta Pajama,Teal Red Plain Kurta Set with Embroidered Collar,SDES856-329,"₹ 2,999"
26,Vedant Fashions Ltd.,Men,Kurta Pajama,Pista Green and Beige Diamond Patterned Kurta Set,CPOSK698-311,"₹ 4,999"
27,Vedant Fashions Ltd.,Men,Kurta Pajama,Melon Orange Floral Printed Kurta Set,SDES903-328,"₹ 2,999"
28,Vedant Fashions Ltd.,Men,Kurta Pajama,Stone Grey Botanical Printed Kurta Set,SOSK634-308,"₹ 3,499"
29,Vedant Fashions Ltd.,Men,Kurta Pajama,Off White Celebration Wear Self Design Kurta P...,SDES651-302,"₹ 5,999"

In [52]:
df.to_csv('ListM.csv', index=True)

In [53]:
for url in product_url[0:30]:
    driver.get(url)
    time.sleep(3)
    

    try:
        Wear_type=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/ul/li[1]/a")
        Weartype.append(Wear_type.text)
    except NoSuchElementException:
        Weartype.append('--------')
   
    try:
        Material_type=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[17]/div/div/div[1]/div/div/div[4]/ul/li[2]")
        Materialtype.append(Material_type.text)
    except NoSuchElementException:
        Materialtype.append('--------')
        
    try:
        Reviews=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[12]/p")
        reviews.append(Reviews.text)
    except NoSuchElementException:
        reviews.append('--------')
        
    try:
        Countryof_origin=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[15]/div/div[1]/div/div/span")
        Countryoforigin.append(Countryof_origin.text)
    except NoSuchElementException:
        Countryoforigin.append("--------")
        
    try:
        Return_time=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[15]/div/div[2]/div/div/span")
        Returntime.append(Return_time.text)
    except NoSuchElementException:
        Returntime.append("--------")
        
    try:
        color_1=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[17]/div/div/div[1]/div/div/div[4]/ul/li[1]")
        color1.append(color_1.text)
    except NoSuchElementException:
        color1.append('--------')
        
    try:
        color_2=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[6]/div/div/div/a[2]/span[1]")
        color2.append(color_2.text)
    except NoSuchElementException:
        color2.append("--------")
        
        
    try:
        Size_1=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[1]")
        Size1.append(Size_1.text)
    except NoSuchElementException:
        Size1.append("--------")
   
    try:
        Size_2=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[2]")
        Size2.append(Size_2.text)
    except NoSuchElementException:
        Size2.append("--------")
        
    try:
        Size_3=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[3]")
        Size3.append(Size_3.text)
    except NoSuchElementException:
        Size3.append("--------")
        
    try:
        Size_4=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[4]")
        Size4.append(Size_4.text)
    except NoSuchElementException:
        Size4.append("--------")
        
    try:
        occasion=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/ul/li[5]/a")
        Occasion.append(occasion.text)
    except NoSuchElementException:
        Occasion.append("--------")

In [54]:
len(Weartype), len(Materialtype), len(reviews), len(Countryoforigin), len(Returntime), len(color1), len(color2), len(Size1), len(Size2), len(Size3), len(Size4), len(Occasion)

(30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30)

In [55]:
data1 = {
    'Wear_type': Weartype,
    'Material_type': Materialtype,
    'Reviews': reviews,
    'color1': color1,
    'color2': color2
     }

In [56]:
df1 = pd.DataFrame(data1)

In [59]:
df1.rename_axis('Sno', inplace=True)

In [60]:
df1.to_csv('ListM1.csv', index=True)

In [61]:
df1

,Wear_type,Material_type,Reviews,color1,color2
Sno,,,,,
0,Kurta Pajama,--------,674 people have viewed the product recently,--------,--------
1,Kurta Pajama,--------,674 people have viewed the product recently,--------,
2,Kurta Pajama,,674 people have viewed the product recently,,
3,Kurta Pajama,,--------,,
4,Kurta Pajama,,674 people have viewed the product recently,,--------
5,Kurta Pajama,,--------,,--------
6,Kurta Pajama,--------,--------,--------,
7,Kurta Pajama,--------,--------,--------,
8,Kurta Pajama,--------,674 people have viewed the product recently,--------,
9,Kurta Pajama,--------,674 people have viewed the product recently,--------,
10,Kurta Pajama,,674 people have viewed the product recently,,
11,Kurta Pajama,--------,674 people have viewed the product recently,--------,
12,Kurta Pajama,--------,674 people have viewed the product recently,--------,
13,Kurta Pajama,,674 people have viewed the product recently,,--------
14,Kurta Pajama,--------,674 people have viewed the product recently,--------,
15,Kurta Pajama,--------,674 people have viewed the product recently,--------,
16,Kurta Pajama,,674 people have viewed the product recently,,--------
17,Kurta Pajama,--------,674 people have viewed the product recently,--------,
18,Kurta Pajama,,674 people have viewed the product recently,,
19,Kurta Pajama,,--------,,
20,Kurta Pajama,,672 people have viewed the product recently,,
21,Kurta Pajama,--------,--------,--------,--------
22,Kurta Pajama,,674 people have viewed the product recently,,
23,Kurta Pajama,,674 people have viewed the product recently,,
24,Kurta Pajama,,674 people have viewed the product recently,,
25,Kurta Pajama,,674 people have viewed the product recently,,--------
26,Kurta Pajama,,674 people have viewed the product recently,,--------
27,Kurta Pajama,,674 people have viewed the product recently,,--------
28,Kurta Pajama,,674 people have viewed the product recently,,--------
29,Kurta Pajama,--------,674 people have viewed the product recently,--------,

In [62]:
data2= {
    'Country_of_origin':Countryoforigin,
    'Return_time':Returntime,
    'Size1':Size1,
    'Size2':Size2,
    'Size3':Size3,
    'Size4':Size4,
    'Occassion':Occasion
    }

In [63]:
df2 = pd.DataFrame(data2)

In [65]:
df2.rename_axis('Sno', inplace=True)

In [66]:
df2['Return_time'] = df2['Return_time'].str.replace('[^\d]', '', regex=True)

In [69]:
df2.to_csv('ListM2.csv', index=True)

In [70]:
df2

    Country_of_origin Return_time Size1 Size2 Size3 Size4     Occassion
Sno
0               India          15     S     M     L    XL  Indo Western
1               India          15     S     M     L    XL  Indo Western
2               India          15     S     M     L    XL  Indo Western
3            --------                 S     M     L    XL  Indo Western
4               India          15     S     M     L    XL  Indo Western
5            --------                 S     M     L    XL  Indo Western
6            --------                 S     M     L    XL  Indo Western
7            --------                 S     M     L    XL  Indo Western
8               India          15     S     M     L    XL  Indo Western
9               India          15     S     M     L    XL  Indo Western
10              India          15     S     M     L    XL  Indo Western
11              India          15     S     M     L    XL  Indo Western
12              India          15     S     M     L    XL  Indo Western
13              India          15     S     M     L    XL  Indo Western
14              India          15     S     M     L    XL  Indo Western
15              India          15     S     M     L    XL  Indo Western
16              India          15     S     M     L    XL  Indo Western
17              India          15     S     M     L    XL  Indo Western
18              India          15     S     M     L    XL  Indo Western
19           --------                 S     M     L    XL  Indo Western
20              India          15     S     M     L    XL  Indo Western
21           --------                 S     M     L    XL  Indo Western
22              India          15     S     M     L    XL  Indo Western
23              India          15     S     M     L    XL  Indo Western
24              India          15     S     M     L    XL  Indo Western
25              India          15     S     M     L    XL  Indo Western
26              India          15     S     M     L    XL  Indo Western
27              India          15     S     M     L    XL  Indo Western
28              India          15     S     M     L    XL  Indo Western
29              India          15     S     M     L    XL  Indo Western

In [72]:
#Extracting first few records for men
for url in product_url[31:61]:
    driver.get(url)
    time.sleep(2)
    

Brandname=[]
Category=[]
Producttype=[]
ProductName=[]
Productcode=[]
Price=[]
Weartype=[]
Materialtype=[]
Returntime=[]
reviews=[]
Countryoforigin=[]
reviews=[]
Occasion=[]
color1=[]
color2=[]
Size1=[]
Size2=[]
Size3=[]
Size4=[]

In [73]:
for url in product_url[31:61]:
    driver.get(url)
    time.sleep(2)
    
    
    try:
        Brand_name=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[6]/div[2]/p")
        Brandname.append(Brand_name.text)
    except NoSuchElementException:
        Brandname.append('--------')
   
    try:
        Cat=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/button/h3")
        Category.append(Cat.text)
    except NoSuchElementException:
        Category.append('--------')
        

    try:
        Product_type=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/ul/li[1]/a")
        Producttype.append(Product_type.text)
    except NoSuchElementException:
        Producttype.append('--------')
        
    try:
        Product_Name=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[1]/div/h1")
        ProductName.append(Product_Name.text)
    except NoSuchElementException:
        ProductName.append("--------")
        
    try:
        Product_code=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[3]/div/span")
        Productcode.append(Product_code.text)
    except NoSuchElementException:
        Productcode.append("--------")
        
    try:
        Price_u=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[2]/div/div/div/span/span/span/h2")
        Price.append(Price_u.text)
    except NoSuchElementException:
        Price.append("--------")

In [74]:
len(Brandname), len(Category), len(Producttype), len(ProductName), len(Productcode), len(Price)

(30, 30, 30, 30, 30, 30)

In [75]:
datan = {
    'Brand': Brandname,
    'Category': Category,
    'Product_type': Producttype,
    'Product_Name': ProductName,
    'Product_code': Productcode,
    'Price': Price
    }

In [76]:
df3 = pd.DataFrame(datan)

In [78]:
df.rename_axis('Sno',inplace=True)

In [83]:
df.to_csv('ListM3.csv', index=True)

In [84]:
df3

,Brand,Category,Product_type,Product_Name,Product_code,Price
0,Vedant Fashions Ltd.,Men,Kurta Pajama,Royal Maroon Printed Kurta Set,CPOSK607-307,"₹ 4,999"
1,Vedant Fashions Ltd.,Men,Kurta Pajama,Grey Kurta Pajama With Golden Motif,SDES515-308,"₹ 3,999"
2,Vedant Fashions Ltd.,Men,Kurta Pajama,Aspen Gold Yellow Chikankari Kurta Set,SDES784-328,"₹ 3,999"
3,Vedant Fashions Ltd.,Men,Kurta Pajama,Rosewater Pink Vertical Striped Kurta Set,SDES860-373,"₹ 3,499"
4,Vedant Fashions Ltd.,Men,Kurta Pajama,Primrose Yellow Chikankari Embroidered Kurta Set,SDES632-324,"₹ 3,999"
5,Vedant Fashions Ltd.,Men,Kurta Pajama,Aquamarine Blue Watercolor Effect Printed Kurt...,CPOSK710-341,"₹ 4,999"
6,Vedant Fashions Ltd.,Men,Kurta Pajama,Berry Wine Patterned Kurta Set,SDES505A-322,"₹ 4,999"
7,Vedant Fashions Ltd.,Men,Kurta Pajama,Blissful Blue and Copper Floral Medallion Patt...,SDES823-326/373,"₹ 3,999"
8,Vedant Fashions Ltd.,Men,Kurta Pajama,Subtle Green Plain Kurta Set,SDES854-334,"₹ 2,999"
9,Vedant Fashions Ltd.,Men,Kurta Pajama,Marble Blue Tree Of Life Print Kurta Set,CPOSK697-326,"₹ 4,999"
10,Vedant Fashions Ltd.,Men,Kurta Pajama,Turquoise Blue Diamond Patterned Chikankari Em...,SDES626-326,"₹ 4,999"
11,Vedant Fashions Ltd.,Men,Kurta Pajama,Sky Blue Festive Kurta Pajama,SDES673-341,"₹ 4,999"
12,Vedant Fashions Ltd.,Men,Kurta Pajama,Pearl River Grey Floral Patterned Kurta Set,SDES673-312,"₹ 4,999"
13,Vedant Fashions Ltd.,Men,Kurta Pajama,Dark Brown Printed Kurta,SOSK629-309,"₹ 3,499"
14,Vedant Fashions Ltd.,Men,Kurta Pajama,White Booti Self Motif Kurta Pajama,SDES761-340,"₹ 4,999"
15,Vedant Fashions Ltd.,Men,Kurta Pajama,Maroon Printed Kurta Set,SDES728-307,"₹ 2,999"
16,Vedant Fashions Ltd.,Men,Kurta Pajama,Sea Green Jacquard Kurta Pajama,SDES677-333,"₹ 3,499"
17,Vedant Fashions Ltd.,Men,Kurta Pajama,Amber Yellow Kurta Set with Floral Embroidered...,SDES877-328,"₹ 2,999"
18,Vedant Fashions Ltd.,Men,Kurta Pajama,Coral Pink Jaal Patterned Kurta Set,SDES871-373,"₹ 3,499"
19,Vedant Fashions Ltd.,Men,Kurta Pajama,Sunrise Orange Floral Spot Patterned Kurta Set,SDES765-328,"₹ 4,999"
20,Vedant Fashions Ltd.,Men,Kurta Pajama,Bottle Green Printed Kurta Pajama,SOSK674-316,"₹ 3,499"
21,Vedant Fashions Ltd.,Men,Kurta Pajama,Navy Blue Ogee Patterned Kurta Set,SDES629-306,"₹ 3,499"
22,Vedant Fashions Ltd.,Men,Kurta Pajama,Light Pink Floral Patterned Kurta Set,SDES807-325,"₹ 6,999"
23,Vedant Fashions Ltd.,Men,Kurta Pajama,Light Pink Striped Kurta Set,SDES872-373,"₹ 3,499"
24,Vedant Fashions Ltd.,Men,Kurta Pajama,Sunrise Yellow Kurta Set with Embroidered Placket,SDES831-328,"₹ 3,999"
25,Vedant Fashions Ltd.,Men,Kurta Pajama,Sunrise Orange Floral Spot Patterned Kurta Set,SDES438-328,"₹ 3,999"
26,Vedant Fashions Ltd.,Men,Kurta Pajama,Blue Plain Kurta Set,SDES615-306,"₹ 3,499"
27,Vedant Fashions Ltd.,Men,Kurta Pajama,Indigo Blue Booti Work Kurta Pajama,CPOSK563-339,"₹ 4,999"
28,Vedant Fashions Ltd.,Men,Kurta Pajama,Aquamarine Blue Sequined Kurta Set,CPOSK654-333,"₹ 4,999"
29,Vedant Fashions Ltd.,Men,Kurta Pajama,Crayola Yellow Polka Dotted Kurta Set,SDES837-324,"₹ 4,999"

In [85]:
for url in product_url[31:61]:
    driver.get(url)
    time.sleep(2)
    

    try:
        Wear_type=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/ul/li[1]/a")
        Weartype.append(Wear_type.text)
    except NoSuchElementException:
        Weartype.append('--------')
   
    try:
        Material_type=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[17]/div/div/div[1]/div/div/div[4]/ul/li[2]")
        Materialtype.append(Material_type.text)
    except NoSuchElementException:
        Materialtype.append('--------')
        
    try:
        Reviews=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[12]/p")
        reviews.append(Reviews.text)
    except NoSuchElementException:
        reviews.append('--------')
        
    try:
        Countryof_origin=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[15]/div/div[1]/div/div/span")
        Countryoforigin.append(Countryof_origin.text)
    except NoSuchElementException:
        Countryoforigin.append("--------")
        
    try:
        Return_time=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[15]/div/div[2]/div/div/span")
        Returntime.append(Return_time.text)
    except NoSuchElementException:
        Returntime.append("--------")
        
    try:
        color_1=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[17]/div/div/div[1]/div/div/div[4]/ul/li[1]")
        color1.append(color_1.text)
    except NoSuchElementException:
        color1.append('--------')
        
    try:
        color_2=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[6]/div/div/div/a[2]/span[1]")
        color2.append(color_2.text)
    except NoSuchElementException:
        color2.append("--------")
        
        
    try:
        Size_1=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[1]")
        Size1.append(Size_1.text)
    except NoSuchElementException:
        Size1.append("--------")
   
    try:
        Size_2=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[2]")
        Size2.append(Size_2.text)
    except NoSuchElementException:
        Size2.append("--------")
        
    try:
        Size_3=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[3]")
        Size3.append(Size_3.text)
    except NoSuchElementException:
        Size3.append("--------")
        
    try:
        Size_4=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[4]")
        Size4.append(Size_4.text)
    except NoSuchElementException:
        Size4.append("--------")
        
    try:
        occasion=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/ul/li[5]/a")
        Occasion.append(occasion.text)
    except NoSuchElementException:
        Occasion.append("--------")

In [86]:
len(Weartype), len(Materialtype), len(reviews), len(Countryoforigin), len(Returntime), len(color1), len(color2), len(Size1), len(Size2), len(Size3), len(Size4), len(Occasion)

(30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30)

In [92]:
datan1 = {
    'Wear_type': Weartype,
    'Material_type': Materialtype,
    'Reviews': reviews,
    'color1': color1,
    'color2': color2
     }

In [93]:
df4 = pd.DataFrame(datan1)

In [94]:
df4.rename_axis('Sno', inplace=True)

In [95]:
df4.to_csv('ListM4.csv', index=True)

In [96]:
df4

,Wear_type,Material_type,Reviews,color1,color2
Sno,,,,,
0,Kurta Pajama,--------,674 people have viewed the product recently,--------,
1,Kurta Pajama,--------,674 people have viewed the product recently,--------,
2,Kurta Pajama,,--------,,
3,Kurta Pajama,,674 people have viewed the product recently,,--------
4,Kurta Pajama,,674 people have viewed the product recently,,
5,Kurta Pajama,--------,--------,--------,
6,Kurta Pajama,--------,--------,--------,
7,Kurta Pajama,,461 people have viewed the product recently,,
8,Kurta Pajama,,674 people have viewed the product recently,,
9,Kurta Pajama,,672 people have viewed the product recently,,--------
10,Kurta Pajama,--------,--------,--------,
11,Kurta Pajama,--------,672 people have viewed the product recently,--------,
12,Kurta Pajama,,461 people have viewed the product recently,,
13,Kurta Pajama,--------,437 people have viewed the product recently,--------,--------
14,Kurta Pajama,--------,461 people have viewed the product recently,--------,--------
15,Kurta Pajama,,674 people have viewed the product recently,,--------
16,Kurta Pajama,--------,674 people have viewed the product recently,--------,
17,Kurta Pajama,--------,--------,--------,--------
18,Kurta Pajama,,278 people have viewed the product recently,,
19,Kurta Pajama,--------,--------,--------,--------
20,Kurta Pajama,--------,437 people have viewed the product recently,--------,--------
21,Kurta Pajama,--------,--------,--------,
22,Kurta Pajama,,437 people have viewed the product recently,,--------
23,Kurta Pajama,,278 people have viewed the product recently,,
24,Kurta Pajama,,674 people have viewed the product recently,,
25,Kurta Pajama,,672 people have viewed the product recently,,
26,Kurta Pajama,,437 people have viewed the product recently,,
27,Kurta Pajama,,437 people have viewed the product recently,,
28,Kurta Pajama,,124 people have viewed the product recently,,
29,Kurta Pajama,,437 people have viewed the product recently,,--------

In [97]:
datan2= {
    'Country_of_origin':Countryoforigin,
    'Return_time':Returntime,
    'Size1':Size1,
    'Size2':Size2,
    'Size3':Size3,
    'Size4':Size4,
    'Occassion':Occasion
    }

In [98]:
df5 = pd.DataFrame(datan2)

In [100]:
df5.rename_axis('Sno', inplace=True)

In [102]:
df5['Return_time'] = df5['Return_time'].str.replace('[^\d]', '', regex=True)

In [105]:
df5.to_csv('ListM5.csv', index=True)

In [104]:
df5

    Country_of_origin Return_time Size1 Size2 Size3 Size4     Occassion
Sno
0               India          15     S     M     L    XL  Indo Western
1               India          15     S     M     L    XL  Indo Western
2            --------                 S     M     L    XL  Indo Western
3               India          15     S     M     L    XL  Indo Western
4               India          15     S     M     L    XL  Indo Western
5            --------                 S     M     L    XL  Indo Western
6            --------                 S     M     L    XL  Indo Western
7               India          15     S     M     L    XL  Indo Western
8               India          15     S     M     L    XL  Indo Western
9               India          15     S     M     L    XL  Indo Western
10           --------                 S     M     L    XL  Indo Western
11              India          15     S     M     L    XL  Indo Western
12              India          15     S     M     L    XL  Indo Western
13              India          15     S     M     L    XL  Indo Western
14              India          15     S     M     L    XL  Indo Western
15              India          15     S     M     L    XL  Indo Western
16              India          15     S     M     L    XL  Indo Western
17           --------                 S     M     L    XL  Indo Western
18              India          15     S     M     L    XL  Indo Western
19           --------                 S     M     L    XL  Indo Western
20              India          15     S     M     L    XL  Indo Western
21           --------                 S     M     L    XL  Indo Western
22              India          15     S     M     L    XL  Indo Western
23              India          15     S     M     L    XL  Indo Western
24              India          15     S     M     L    XL  Indo Western
25              India          15     S     M     L    XL  Indo Western
26              India          15     S     M     L    XL  Indo Western
27              India          15     S     M     L    XL  Indo Western
28              India          15     S     M     L    XL  Indo Western
29              India          15     S     M     L    XL  Indo Western

In [106]:
#Extracting first few records for men
for url in product_url[62:92]:
    driver.get(url)
    time.sleep(2)
    

Brandname=[]
Category=[]
Producttype=[]
ProductName=[]
Productcode=[]
Price=[]
Weartype=[]
Materialtype=[]
Returntime=[]
reviews=[]
Countryoforigin=[]
reviews=[]
Occasion=[]
color1=[]
color2=[]
Size1=[]
Size2=[]
Size3=[]
Size4=[]

In [107]:
for url in product_url[62:92]:
    driver.get(url)
    time.sleep(2)
    
    
    try:
        Brand_name=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[6]/div[2]/p")
        Brandname.append(Brand_name.text)
    except NoSuchElementException:
        Brandname.append('--------')
   
    try:
        Cat=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/button/h3")
        Category.append(Cat.text)
    except NoSuchElementException:
        Category.append('--------')
        

    try:
        Product_type=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/ul/li[1]/a")
        Producttype.append(Product_type.text)
    except NoSuchElementException:
        Producttype.append('--------')
        
    try:
        Product_Name=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[1]/div/h1")
        ProductName.append(Product_Name.text)
    except NoSuchElementException:
        ProductName.append("--------")
        
    try:
        Product_code=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[3]/div/span")
        Productcode.append(Product_code.text)
    except NoSuchElementException:
        Productcode.append("--------")
        
    try:
        Price_u=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[2]/div/div/div/span/span/span/h2")
        Price.append(Price_u.text)
    except NoSuchElementException:
        Price.append("--------")

In [108]:
len(Brandname), len(Category), len(Producttype), len(ProductName), len(Productcode), len(Price)

(30, 30, 30, 30, 30, 30)

In [109]:
datam = {
    'Brand': Brandname,
    'Category': Category,
    'Product_type': Producttype,
    'Product_Name': ProductName,
    'Product_code': Productcode,
    'Price': Price
    }

In [110]:
df6 = pd.DataFrame(datam)

In [111]:
df6.rename_axis('Sno',inplace=True)

In [115]:
df6.to_csv('ListM6.csv', index=True)

In [116]:
df6

,Brand,Category,Product_type,Product_Name,Product_code,Price
Sno,,,,,,
0,Vedant Fashions Ltd.,Men,Kurta Pajama,Summer Green Embellished Kurta Set,SDES436-334,"₹ 3,999"
1,Vedant Fashions Ltd.,Men,Kurta Pajama,Merlot Red Jacquard Kurta Set,SDES093-307,"₹ 2,999"
2,Vedant Fashions Ltd.,Men,Kurta Pajama,Basic Cream Kurta Set,CPOSK297-303,"₹ 2,999"
3,Vedant Fashions Ltd.,Men,Kurta Pajama,Black Self Embroidered Kurta Pajama,SDES784-310,"₹ 3,999"
4,Vedant Fashions Ltd.,Men,Kurta Pajama,Salt White Solid Kurta Set,M301114-302,"₹ 1,999"
5,Vedant Fashions Ltd.,Men,Kurta Pajama,Amber Yellow Self Design Kurta Set,S952704-328,"₹ 4,999"
6,Vedant Fashions Ltd.,Men,Kurta Pajama,Feroze Self Design Kurta Set,S952783-326,"₹ 2,999"
7,Vedant Fashions Ltd.,Men,Kurta Pajama,Pastel Pink Kurta With Embroidery Work,SDES438-319,"₹ 3,999"
8,Vedant Fashions Ltd.,Men,Kurta Pajama,Beige Jacquard Kurta Set,CPOSK273-303,"₹ 4,999"
9,Vedant Fashions Ltd.,Men,Kurta Pajama,Pomegranate Red Jacquard Patterned Kurta Set,SDES515-307,"₹ 3,999"
10,Vedant Fashions Ltd.,Men,Kurta Pajama,Indigo Blue Self Chequered Kurta,M301110-306,"₹ 1,999"
11,Vedant Fashions Ltd.,Men,Kurta Pajama,Wine Self Design Kurta With Black Churidar,S952612-322,"₹ 3,999"
12,Vedant Fashions Ltd.,Men,Kurta Pajama,Pearl White Solid Kurta Set,M306041-101,"₹ 2,499"
13,Vedant Fashions Ltd.,Men,Kurta Pajama,Classic Black Kurta,S952780-310,"₹ 2,999"
14,Vedant Fashions Ltd.,Men,Kurta Pajama,Mustard Yellow Plain Kurta Set With Neck Detai...,S952611-328,"₹ 1,999"
15,Vedant Fashions Ltd.,Men,Kurta Pajama,Traditional Chikankari Blue Kurta Set,SDES466-306,"₹ 3,999"
16,Vedant Fashions Ltd.,Men,Kurta Pajama,Dusty Rose Pink Jacquard Patterned Kurta Set,SDES756-373,"₹ 3,999"
17,Vedant Fashions Ltd.,Men,Kurta Pajama,Light Green Solid Kurta Set,M301111-334,"₹ 1,999"
18,Vedant Fashions Ltd.,Men,Kurta Pajama,Deep Mahogany Brown Embellished Buttoned Kurta...,SDES787-348,"₹ 1,999"
19,Vedant Fashions Ltd.,Men,Kurta Pajama,Peacock Blue Jacquard Patterned Kurta Set,SDES621-327,"₹ 3,999"
20,Vedant Fashions Ltd.,Men,Kurta Pajama,Ivory White Plain Kurta Set,M201008-101,"₹ 2,499"
21,Vedant Fashions Ltd.,Men,Kurta Pajama,Seafoam Green Solid Kurta Set With Neck Detailing,M301065-333,"₹ 1,999"
22,Vedant Fashions Ltd.,Men,Kurta Pajama,Off White Plain Kurta Set,S952746-340,"₹ 2,499"
23,Vedant Fashions Ltd.,Men,Kurta Pajama,Aqua Green Chikankari Kurta Pajama,SDES624-333,"₹ 3,999"
24,Vedant Fashions Ltd.,Men,Kurta Pajama,Indigo Blue Booti Work Kurta Set,SDES584-306,"₹ 2,999"
25,Vedant Fashions Ltd.,Men,Kurta Pajama,Aquamarine Blue Chikankari Kurta Set,SDES784-333,"₹ 3,999"
26,Vedant Fashions Ltd.,Men,Kurta Pajama,Sand White Jacquard Patterned Kurta Set,SDES661-302,"₹ 2,999"
27,Vedant Fashions Ltd.,Men,Kurta Pajama,Merlot Red Jacquard Kurta Pajama,CPOSK543-307,"₹ 3,999"
28,Vedant Fashions Ltd.,Men,Kurta Pajama,Light Green Jacquard Kurta Set,SDES475-334,"₹ 3,999"
29,Vedant Fashions Ltd.,Men,Kurta Pajama,Wine Self Floral Motif Kurta Set,S952739-322,"₹ 3,999"

In [117]:
for url in product_url[62:92]:
    driver.get(url)
    time.sleep(2)
    

    try:
        Wear_type=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/ul/li[1]/a")
        Weartype.append(Wear_type.text)
    except NoSuchElementException:
        Weartype.append('--------')
   
    try:
        Material_type=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[17]/div/div/div[1]/div/div/div[4]/ul/li[2]")
        Materialtype.append(Material_type.text)
    except NoSuchElementException:
        Materialtype.append('--------')
        
    try:
        Reviews=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[12]/p")
        reviews.append(Reviews.text)
    except NoSuchElementException:
        reviews.append('--------')
        
    try:
        Countryof_origin=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[15]/div/div[1]/div/div/span")
        Countryoforigin.append(Countryof_origin.text)
    except NoSuchElementException:
        Countryoforigin.append("--------")
        
    try:
        Return_time=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[15]/div/div[2]/div/div/span")
        Returntime.append(Return_time.text)
    except NoSuchElementException:
        Returntime.append("--------")
        
    try:
        color_1=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[17]/div/div/div[1]/div/div/div[4]/ul/li[1]")
        color1.append(color_1.text)
    except NoSuchElementException:
        color1.append('--------')
        
    try:
        color_2=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[6]/div/div/div/a[2]/span[1]")
        color2.append(color_2.text)
    except NoSuchElementException:
        color2.append("--------")
        
        
    try:
        Size_1=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[1]")
        Size1.append(Size_1.text)
    except NoSuchElementException:
        Size1.append("--------")
   
    try:
        Size_2=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[2]")
        Size2.append(Size_2.text)
    except NoSuchElementException:
        Size2.append("--------")
        
    try:
        Size_3=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[3]")
        Size3.append(Size_3.text)
    except NoSuchElementException:
        Size3.append("--------")
        
    try:
        Size_4=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[4]")
        Size4.append(Size_4.text)
    except NoSuchElementException:
        Size4.append("--------")
        
    try:
        occasion=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/ul/li[5]/a")
        Occasion.append(occasion.text)
    except NoSuchElementException:
        Occasion.append("--------")

In [118]:
len(Weartype), len(Materialtype), len(reviews), len(Countryoforigin), len(Returntime), len(color1), len(color2), len(Size1), len(Size2), len(Size3), len(Size4), len(Occasion)

(30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30)

In [119]:
datam1 = {
    'Wear_type': Weartype,
    'Material_type': Materialtype,
    'Reviews': reviews,
    'color1': color1,
    'color2': color2
     }

In [120]:
df7 = pd.DataFrame(datam1)

In [121]:
df7.rename_axis('Sno', inplace=True)

In [123]:
df7.to_csv('ListM7.csv', index=True)

In [122]:
df7

,Wear_type,Material_type,Reviews,color1,color2
Sno,,,,,
0,Kurta Pajama,,278 people have viewed the product recently,,
1,Kurta Pajama,--------,674 people have viewed the product recently,--------,
2,Kurta Pajama,--------,674 people have viewed the product recently,--------,--------
3,Kurta Pajama,--------,674 people have viewed the product recently,--------,
4,Kurta Pajama,--------,674 people have viewed the product recently,--------,--------
5,Kurta Pajama,,--------,,--------
6,Kurta Pajama,--------,674 people have viewed the product recently,--------,--------
7,Kurta Pajama,--------,674 people have viewed the product recently,--------,
8,Kurta Pajama,--------,--------,--------,--------
9,Kurta Pajama,--------,674 people have viewed the product recently,--------,
10,Kurta Pajama,--------,674 people have viewed the product recently,--------,--------
11,Kurta Pajama,--------,674 people have viewed the product recently,--------,
12,Kurta Pajama,,--------,,--------
13,Kurta Pajama,,--------,,--------
14,Kurta Pajama,--------,386 people have viewed the product recently,--------,--------
15,Kurta Pajama,,--------,,
16,Kurta Pajama,--------,674 people have viewed the product recently,--------,--------
17,Kurta Pajama,,437 people have viewed the product recently,,--------
18,Kurta Pajama,--------,672 people have viewed the product recently,--------,--------
19,Kurta Pajama,--------,674 people have viewed the product recently,--------,--------
20,Kurta Pajama,--------,278 people have viewed the product recently,--------,--------
21,Kurta Pajama,--------,--------,--------,--------
22,Kurta Pajama,--------,672 people have viewed the product recently,--------,--------
23,Kurta Pajama,--------,672 people have viewed the product recently,--------,
24,Kurta Pajama,--------,--------,--------,--------
25,Kurta Pajama,,--------,,
26,Kurta Pajama,--------,124 people have viewed the product recently,--------,--------
27,Kurta Pajama,--------,672 people have viewed the product recently,--------,
28,Kurta Pajama,--------,674 people have viewed the product recently,--------,--------
29,Kurta Pajama,--------,437 people have viewed the product recently,--------,--------

In [124]:
datam2= {
    'Country_of_origin':Countryoforigin,
    'Return_time':Returntime,
    'Size1':Size1,
    'Size2':Size2,
    'Size3':Size3,
    'Size4':Size4,
    'Occassion':Occasion
    }

In [125]:
df8 = pd.DataFrame(datam2)

In [127]:
df8.rename_axis('Sno', inplace=True)

In [128]:
df8['Return_time'] = df8['Return_time'].str.replace('[^\d]', '', regex=True)

In [131]:
df8.to_csv('ListM8.csv', index=True)

In [132]:
df8

    Country_of_origin Return_time Size1 Size2 Size3 Size4     Occassion
Sno
0               India          15     S     M     L    XL  Indo Western
1               India          15     S     M     L    XL  Indo Western
2               India          15     S     M     L    XL  Indo Western
3               India          15     S     M     L    XL  Indo Western
4               India          15     S     M     L    XL  Indo Western
5            --------                 S     M     L    XL  Indo Western
6               India          15     S     M     L    XL  Indo Western
7               India          15     S     M     L    XL  Indo Western
8            --------                 S     M     L    XL  Indo Western
9               India          15     S     M     L    XL  Indo Western
10              India          15     S     M     L    XL  Indo Western
11              India          15     S     M     L    XL  Indo Western
12           --------                 S     M     L    XL  Indo Western
13           --------                 S     M     L    XL  Indo Western
14              India          15     S     M     L    XL  Indo Western
15           --------                 S     M     L    XL  Indo Western
16              India          15     S     M     L    XL  Indo Western
17              India          15     S     M     L    XL  Indo Western
18              India          15     S     M     L    XL  Indo Western
19              India          15     S     M     L    XL  Indo Western
20              India          15     S     M     L    XL  Indo Western
21           --------                 S     M     L    XL  Indo Western
22              India          15     S     M     L    XL  Indo Western
23              India          15     S     M     L    XL  Indo Western
24           --------                 S     M     L    XL  Indo Western
25           --------                 S     M     L    XL  Indo Western
26              India          15     S     M     L    XL  Indo Western
27              India          15     S     M     L    XL  Indo Western
28              India          15     S     M     L    XL  Indo Western
29              India          15     S     M     L    XL  Indo Western

In [133]:
#Extracting first few records for men
for url in product_url[92:122]:
    driver.get(url)
    time.sleep(2)
    

Brandname=[]
Category=[]
Producttype=[]
ProductName=[]
Productcode=[]
Price=[]
Weartype=[]
Materialtype=[]
Returntime=[]
reviews=[]
Countryoforigin=[]
reviews=[]
Occasion=[]
color1=[]
color2=[]
Size1=[]
Size2=[]
Size3=[]
Size4=[]

In [134]:
for url in product_url[92:122]:
    driver.get(url)
    time.sleep(2)
    
    
    try:
        Brand_name=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[6]/div[2]/p")
        Brandname.append(Brand_name.text)
    except NoSuchElementException:
        Brandname.append('--------')
   
    try:
        Cat=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/button/h3")
        Category.append(Cat.text)
    except NoSuchElementException:
        Category.append('--------')
        

    try:
        Product_type=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/ul/li[1]/a")
        Producttype.append(Product_type.text)
    except NoSuchElementException:
        Producttype.append('--------')
        
    try:
        Product_Name=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[1]/div/h1")
        ProductName.append(Product_Name.text)
    except NoSuchElementException:
        ProductName.append("--------")
        
    try:
        Product_code=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[3]/div/span")
        Productcode.append(Product_code.text)
    except NoSuchElementException:
        Productcode.append("--------")
        
    try:
        Price_u=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[2]/div/div/div/span/span/span/h2")
        Price.append(Price_u.text)
    except NoSuchElementException:
        Price.append("--------")

In [135]:
len(Brandname), len(Category), len(Producttype), len(ProductName), len(Productcode), len(Price)

(30, 30, 30, 30, 30, 30)

In [136]:
datap = {
    'Brand': Brandname,
    'Category': Category,
    'Product_type': Producttype,
    'Product_Name': ProductName,
    'Product_code': Productcode,
    'Price': Price
    }

In [137]:
dfn1 = pd.DataFrame(datap)

In [138]:
dfn1.rename_axis('Sno',inplace=True)

In [143]:
dfn1.to_csv('ListM9.csv', index=True)

In [144]:
dfn1

,Brand,Category,Product_type,Product_Name,Product_code,Price
Sno,,,,,,
0,Vedant Fashions Ltd.,Men,Kurta Pajama,Black Solid Kurta Set,SDES524-310,"₹ 3,499"
1,Vedant Fashions Ltd.,Men,Kurta Pajama,Shell White Embellished Button Kurta Set,SDES603-301,"₹ 3,499"
2,Vedant Fashions Ltd.,Men,Kurta Pajama,Scarlet Red Kurta Set With Neck Detailing,CPOSK296-307,"₹ 2,999"
3,Vedant Fashions Ltd.,Men,Kurta Pajama,Fern Green Jacquard Kurta Pajama,SDES676-317,"₹ 2,999"
4,Vedant Fashions Ltd.,Men,Kurta Pajama,Brilliant White Placket Detailed Kurta Set,SDES714-301,"₹ 3,499"
5,Vedant Fashions Ltd.,Men,Kurta Pajama,Mint Green Chikankari Embroidered Kurta Set,SOSK610-333,"₹ 5,999"
6,Vedant Fashions Ltd.,Men,Kurta Pajama,Black Self Design Kurta Pajama,SDES589-310,"₹ 2,999"
7,Vedant Fashions Ltd.,Men,Kurta Pajama,Faded Green Printed Kurta Set,SDES520-317,"₹ 2,499"
8,Vedant Fashions Ltd.,Men,Kurta Pajama,Cream White Patterned Placket Kurta Set,SDES657-302,"₹ 3,999"
9,Vedant Fashions Ltd.,Men,Kurta Pajama,Ruby Red Plain Kurta Set,M301063-307,"₹ 1,999"
10,Vedant Fashions Ltd.,Men,Kurta Pajama,Yellow Self Design Kurta Pajama,M302227-324,"₹ 2,999"
11,Vedant Fashions Ltd.,Men,Kurta Pajama,Pastel Green Self Design Kurta Set,SDES436-317,"₹ 3,999"
12,Vedant Fashions Ltd.,Men,Kurta Pajama,Sage Green Self Checquered Kurta Pajama,SDES643-317,"₹ 3,499"
13,Vedant Fashions Ltd.,Men,Kurta Pajama,Mauve Wine Dotted Patterned Kurta Set,SDES723-322,"₹ 3,499"
14,Vedant Fashions Ltd.,Men,Kurta Pajama,Rust Pink Self Design Kurta Set,SDES408-319,"₹ 2,999"
15,Vedant Fashions Ltd.,Men,Kurta Pajama,Rose Pink Self Motif Kurta Set,M301107-319,"₹ 1,999"
16,Vedant Fashions Ltd.,Men,Kurta Pajama,Off-white Contrast Placket Kurta Set,SDES656-302,"₹ 3,999"
17,Vedant Fashions Ltd.,Men,Kurta Pajama,Daffodil Yellow Dotted Patterned Kurta Set,SDES767-324,"₹ 2,999"
18,Vedant Fashions Ltd.,Men,Kurta Pajama,Mint Green Jacquard Kurta Set,CPOSK399-334,"₹ 3,999"
19,Vedant Fashions Ltd.,Men,Kurta Pajama,Butterfly Green Jacquard Pattern Kurta Set,SOSK604-334,"₹ 5,999"
20,Vedant Fashions Ltd.,Men,Kurta Pajama,Squash Yellow Patterned Placket Kurta Set,M302241-324,"₹ 2,999"
21,Vedant Fashions Ltd.,Men,Kurta Pajama,Sunrise Orange Placket Detailed Kurta Set,SDES713-328,"₹ 3,499"
22,Vedant Fashions Ltd.,Men,Kurta Pajama,Green Kurta With Embroidered Collar,SDES712-317,"₹ 2,999"
23,Vedant Fashions Ltd.,Men,Kurta Pajama,Candlelight Orange Placket Detailed Kurta Set,SDES800-328,"₹ 3,499"
24,Vedant Fashions Ltd.,Men,Kurta Pajama,Candlelight Orange Placket Detailed Kurta Set,SDES715-328,"₹ 3,499"
25,Vedant Fashions Ltd.,Men,Kurta Pajama,Dark Blue Chikankari Kurta,CPOSK612-339,"₹ 3,999"
26,Vedant Fashions Ltd.,Men,Kurta Pajama,Bright White Floral Chikankari Kurta Set,CPOSK612-340,"₹ 3,999"
27,Vedant Fashions Ltd.,Men,Kurta Pajama,Black Chikankari Kurta Set,CPOSK612-310,"₹ 3,999"
28,Vedant Fashions Ltd.,Men,Kurta Pajama,Jamun Purple Sequin Embellished Chikankari Kur...,CPOSK612-313,"₹ 3,999"
29,Vedant Fashions Ltd.,Men,Kurta Pajama,Quartz Pink Floral Chikankari Embroidered Kurt...,CPOSK612-373,"₹ 3,999"

In [145]:
for url in product_url[92:122]:
    driver.get(url)
    time.sleep(2)
    

    try:
        Wear_type=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/ul/li[1]/a")
        Weartype.append(Wear_type.text)
    except NoSuchElementException:
        Weartype.append('--------')
   
    try:
        Material_type=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[17]/div/div/div[1]/div/div/div[4]/ul/li[2]")
        Materialtype.append(Material_type.text)
    except NoSuchElementException:
        Materialtype.append('--------')
        
    try:
        Reviews=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[12]/p")
        reviews.append(Reviews.text)
    except NoSuchElementException:
        reviews.append('--------')
        
    try:
        Countryof_origin=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[15]/div/div[1]/div/div/span")
        Countryoforigin.append(Countryof_origin.text)
    except NoSuchElementException:
        Countryoforigin.append("--------")
        
    try:
        Return_time=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[15]/div/div[2]/div/div/span")
        Returntime.append(Return_time.text)
    except NoSuchElementException:
        Returntime.append("--------")
        
    try:
        color_1=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[17]/div/div/div[1]/div/div/div[4]/ul/li[1]")
        color1.append(color_1.text)
    except NoSuchElementException:
        color1.append('--------')
        
    try:
        color_2=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[6]/div/div/div/a[2]/span[1]")
        color2.append(color_2.text)
    except NoSuchElementException:
        color2.append("--------")
        
        
    try:
        Size_1=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[1]")
        Size1.append(Size_1.text)
    except NoSuchElementException:
        Size1.append("--------")
   
    try:
        Size_2=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[2]")
        Size2.append(Size_2.text)
    except NoSuchElementException:
        Size2.append("--------")
        
    try:
        Size_3=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[3]")
        Size3.append(Size_3.text)
    except NoSuchElementException:
        Size3.append("--------")
        
    try:
        Size_4=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[4]")
        Size4.append(Size_4.text)
    except NoSuchElementException:
        Size4.append("--------")
        
    try:
        occasion=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/ul/li[5]/a")
        Occasion.append(occasion.text)
    except NoSuchElementException:
        Occasion.append("--------")

In [146]:
len(Weartype), len(Materialtype), len(reviews), len(Countryoforigin), len(Returntime), len(color1), len(color2), len(Size1), len(Size2), len(Size3), len(Size4), len(Occasion)

(30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30)

In [147]:
datap1 = {
    'Wear_type': Weartype,
    'Material_type': Materialtype,
    'Reviews': reviews,
    'color1': color1,
    'color2': color2
     }

In [148]:
dfn2 = pd.DataFrame(datap1)

In [149]:
dfn2.rename_axis('Sno', inplace=True)

In [151]:
dfn2.to_csv('ListM10.csv', index=True)

In [150]:
dfn2

,Wear_type,Material_type,Reviews,color1,color2
Sno,,,,,
0,Kurta Pajama,--------,224 people have viewed the product recently,--------,
1,Kurta Pajama,,--------,,
2,Kurta Pajama,--------,224 people have viewed the product recently,--------,
3,Kurta Pajama,--------,672 people have viewed the product recently,--------,--------
4,Kurta Pajama,--------,124 people have viewed the product recently,--------,--------
5,Kurta Pajama,--------,278 people have viewed the product recently,--------,
6,Kurta Pajama,--------,278 people have viewed the product recently,--------,--------
7,Kurta Pajama,--------,224 people have viewed the product recently,--------,--------
8,Kurta Pajama,--------,124 people have viewed the product recently,--------,--------
9,Kurta Pajama,,437 people have viewed the product recently,,--------
10,Kurta Pajama,--------,278 people have viewed the product recently,--------,
11,Kurta Pajama,--------,278 people have viewed the product recently,--------,
12,Kurta Pajama,--------,124 people have viewed the product recently,--------,
13,Kurta Pajama,--------,224 people have viewed the product recently,--------,--------
14,Kurta Pajama,,437 people have viewed the product recently,,--------
15,Kurta Pajama,--------,--------,--------,--------
16,Kurta Pajama,,--------,,--------
17,Kurta Pajama,,124 people have viewed the product recently,,--------
18,Kurta Pajama,--------,--------,--------,
19,Kurta Pajama,,--------,,--------
20,Kurta Pajama,--------,224 people have viewed the product recently,--------,--------
21,Kurta Pajama,--------,124 people have viewed the product recently,--------,--------
22,Kurta Pajama,,--------,,--------
23,Kurta Pajama,,--------,,--------
24,Kurta Pajama,,--------,,
25,Kurta Pajama,,674 people have viewed the product recently,,
26,Kurta Pajama,,674 people have viewed the product recently,,
27,Kurta Pajama,--------,674 people have viewed the product recently,--------,
28,Kurta Pajama,--------,674 people have viewed the product recently,--------,
29,Kurta Pajama,,674 people have viewed the product recently,,

In [152]:
datap2= {
    'Country_of_origin':Countryoforigin,
    'Return_time':Returntime,
    'Size1':Size1,
    'Size2':Size2,
    'Size3':Size3,
    'Size4':Size4,
    'Occassion':Occasion
    }

In [153]:
dfn3 = pd.DataFrame(datap2)

In [154]:
dfn3.rename_axis('Sno', inplace=True)

In [155]:
dfn3['Return_time'] = dfn3['Return_time'].str.replace('[^\d]', '', regex=True)

In [158]:
dfn3.to_csv('ListM11.csv', index=True)

In [157]:
dfn3

    Country_of_origin Return_time Size1 Size2 Size3 Size4     Occassion
Sno
0               India          15     S     M     L    XL  Indo Western
1            --------                 S     M     L    XL  Indo Western
2               India          15     S     M     L    XL  Indo Western
3               India          15     S     M     L    XL  Indo Western
4               India          15     S     M     L    XL  Indo Western
5               India          15     S     M     L    XL  Indo Western
6               India          15     S     M     L    XL  Indo Western
7               India          15     S     M     L    XL  Indo Western
8               India          15     S     M     L    XL  Indo Western
9               India          15     S     M     L    XL  Indo Western
10              India          15     S     M     L    XL  Indo Western
11              India          15     S     M     L    XL  Indo Western
12              India          15     S     M     L    XL  Indo Western
13              India          15     S     M     L    XL  Indo Western
14              India          15     S     M     L    XL  Indo Western
15           --------                 S     M     L    XL  Indo Western
16           --------                 S     M     L    XL  Indo Western
17              India          15     S     M     L    XL  Indo Western
18           --------                 S     M     L    XL  Indo Western
19           --------                 S     M     L    XL  Indo Western
20              India          15     S     M     L    XL  Indo Western
21              India          15     S     M     L    XL  Indo Western
22           --------                 S     M     L    XL  Indo Western
23           --------                 S     M     L    XL  Indo Western
24           --------                 S     M     L    XL  Indo Western
25              India          15     S     M     L    XL  Indo Western
26              India          15     S     M     L    XL  Indo Western
27              India          15     S     M     L    XL  Indo Western
28              India          15     S     M     L    XL  Indo Western
29              India          15     S     M     L    XL  Indo Western

In [159]:
#Extracting first few records for men
for url in product_url[122:152]:
    driver.get(url)
    time.sleep(2)
    

Brandname=[]
Category=[]
Producttype=[]
ProductName=[]
Productcode=[]
Price=[]
Weartype=[]
Materialtype=[]
Returntime=[]
reviews=[]
Countryoforigin=[]
reviews=[]
Occasion=[]
color1=[]
color2=[]
Size1=[]
Size2=[]
Size3=[]
Size4=[]

In [160]:
for url in product_url[122:152]:
    driver.get(url)
    time.sleep(2)
    
    
    try:
        Brand_name=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[6]/div[2]/p")
        Brandname.append(Brand_name.text)
    except NoSuchElementException:
        Brandname.append('--------')
   
    try:
        Cat=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/button/h3")
        Category.append(Cat.text)
    except NoSuchElementException:
        Category.append('--------')
        

    try:
        Product_type=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/ul/li[1]/a")
        Producttype.append(Product_type.text)
    except NoSuchElementException:
        Producttype.append('--------')
        
    try:
        Product_Name=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[1]/div/h1")
        ProductName.append(Product_Name.text)
    except NoSuchElementException:
        ProductName.append("--------")
        
    try:
        Product_code=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[3]/div/span")
        Productcode.append(Product_code.text)
    except NoSuchElementException:
        Productcode.append("--------")
        
    try:
        Price_u=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[2]/div/div/div/span/span/span/h2")
        Price.append(Price_u.text)
    except NoSuchElementException:
        Price.append("--------")

In [161]:
len(Brandname), len(Category), len(Producttype), len(ProductName), len(Productcode), len(Price)

(30, 30, 30, 30, 30, 30)

In [162]:
dataq = {
    'Brand': Brandname,
    'Category': Category,
    'Product_type': Producttype,
    'Product_Name': ProductName,
    'Product_code': Productcode,
    'Price': Price
    }

In [163]:
dfn4 = pd.DataFrame(dataq)

In [169]:
dfn4.to_csv('ListM12.csv', index=True)

In [168]:
dfn4

,Brand,Category,Product_type,Product_Name,Product_code,Price
0,Vedant Fashions Ltd.,Men,Kurta Pajama,Teal Green Self Striped Kurta Set,SDES993-327,"₹ 2,499"
1,Vedant Fashions Ltd.,Men,Kurta Pajama,Forest Green Chikankari Embroidered Sequined K...,SDES820-316,"₹ 4,999"
2,Vedant Fashions Ltd.,Men,Kurta Pajama,Pastel Turquoise Blue Floral Chikankari Patter...,CPOSK612-317,"₹ 3,999"
3,Vedant Fashions Ltd.,Men,Kurta Pajama,Midnight Blue Sequined Kurta Set,SDES820-306,"₹ 4,999"
4,Vedant Fashions Ltd.,Men,Kurta Pajama,Powder Blue Sequin Embellished Chikankari Kurt...,CPOSK612-341,"₹ 3,999"
5,Vedant Fashions Ltd.,Men,Kurta Pajama,Forest Green Chikankari Embroidered Sequined K...,CPOSK612-316,"₹ 3,999"
6,Vedant Fashions Ltd.,Men,Kurta Pajama,Sunglow Yellow Chikankari Embroidered Sequinne...,SDES820-328,"₹ 4,999"
7,Vedant Fashions Ltd.,Men,Kurta Pajama,Serenity Blue Chikankari Embroidered Kurta Set,SDES609-321,"₹ 4,999"
8,Vedant Fashions Ltd.,Men,Kurta Pajama,Lime Yellow Chikankari Kurta Set,CPOSK612-324,"₹ 3,999"
9,Vedant Fashions Ltd.,Men,Kurta Pajama,Ash Grey Chikankari Embroidered Sequinned Kurt...,SDES820-308,"₹ 4,999"
10,Vedant Fashions Ltd.,Men,Kurta Pajama,Ice Blue Ombre Effect Floral Lattice Printed K...,KL12108-341,"₹ 3,999"
11,Vedant Fashions Ltd.,Men,Kurta Pajama,Star White Chikankari Embroidered Sequinned Ku...,SDES820-301,"₹ 4,999"
12,Vedant Fashions Ltd.,Men,Kurta Pajama,Jamun Purple Jaal Patterned Chikankari Kurta Set,SDES784-313,"₹ 3,999"
13,Vedant Fashions Ltd.,Men,Kurta Pajama,Soft Green Botanical Printed Kurta Set,SOSK636-311,"₹ 3,499"
14,Vedant Fashions Ltd.,Men,Kurta Pajama,Amaranth Pink Chikankari Jaal Patterned Kurta Set,SDES784-373,"₹ 3,999"
15,Vedant Fashions Ltd.,Men,Kurta Pajama,Dove Grey Chikankari Sequined Kurta Set,CPOSK699-312,"₹ 4,999"
16,Vedant Fashions Ltd.,Men,Kurta Pajama,Lilac Purple Sequined Kurta Set,SDES962-382,"₹ 4,999"
17,Vedant Fashions Ltd.,Men,Kurta Pajama,Light Beige Zari Bordered Traditional South In...,SOSK092-303,"₹ 4,999"
18,Vedant Fashions Ltd.,Men,Kurta Pajama,Melon Peach and Cream Zari Detailed Traditiona...,SOSK739-319,"₹ 4,999"
19,Vedant Fashions Ltd.,Men,Kurta Pajama,Pristine White Self Striped Kurta Set,SDES993-301,"₹ 2,499"
20,Vedant Fashions Ltd.,Men,Kurta Pajama,Mehendi Green Self Patterned Kurta Set,SDES925-316,"₹ 2,999"
21,Vedant Fashions Ltd.,Men,Kurta Pajama,Bright Mustard Chikankari Sequinned Kurta Set,SDES939-328,"₹ 4,999"
22,Vedant Fashions Ltd.,Men,Kurta Pajama,Biscuit Colour Plain Kurta Set,SDES887-303,"₹ 2,999"
23,Vedant Fashions Ltd.,Men,Kurta Pajama,Lavender Medallion Printed Kurta Set,CPOSK663-313,"₹ 4,999"
24,Vedant Fashions Ltd.,Men,Kurta Pajama,Soft White Floral Sequin Embroidered Kurta Set,SDES933-340,"₹ 4,999"
25,Vedant Fashions Ltd.,Men,Kurta Pajama,Golden Jacquard Printed Kurta Set,SDES846-303,"₹ 2,999"
26,Vedant Fashions Ltd.,Men,Kurta Pajama,Antique White Angrakha Style Diamond Printed K...,KL12111-302,"₹ 3,499"
27,Vedant Fashions Ltd.,Men,Kurta Pajama,Soft Blue Medallion Print Kurta Set,CPOSK663-341,"₹ 4,999"
28,Vedant Fashions Ltd.,Men,Kurta Pajama,Ivory Cream Detailed Traditional South Indian ...,SOSK712-302,"₹ 4,999"
29,Vedant Fashions Ltd.,Men,Kurta Pajama,Maroon Self Patterned Kurta Set,SDES993-307,"₹ 2,499"

In [170]:
for url in product_url[122:152]:
    driver.get(url)
    time.sleep(2)
    

    try:
        Wear_type=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/ul/li[1]/a")
        Weartype.append(Wear_type.text)
    except NoSuchElementException:
        Weartype.append('--------')
   
    try:
        Material_type=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[17]/div/div/div[1]/div/div/div[4]/ul/li[2]")
        Materialtype.append(Material_type.text)
    except NoSuchElementException:
        Materialtype.append('--------')
        
    try:
        Reviews=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[12]/p")
        reviews.append(Reviews.text)
    except NoSuchElementException:
        reviews.append('--------')
        
    try:
        Countryof_origin=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[15]/div/div[1]/div/div/span")
        Countryoforigin.append(Countryof_origin.text)
    except NoSuchElementException:
        Countryoforigin.append("--------")
        
    try:
        Return_time=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[15]/div/div[2]/div/div/span")
        Returntime.append(Return_time.text)
    except NoSuchElementException:
        Returntime.append("--------")
        
    try:
        color_1=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[17]/div/div/div[1]/div/div/div[4]/ul/li[1]")
        color1.append(color_1.text)
    except NoSuchElementException:
        color1.append('--------')
        
    try:
        color_2=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[6]/div/div/div/a[2]/span[1]")
        color2.append(color_2.text)
    except NoSuchElementException:
        color2.append("--------")
        
        
    try:
        Size_1=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[1]")
        Size1.append(Size_1.text)
    except NoSuchElementException:
        Size1.append("--------")
   
    try:
        Size_2=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[2]")
        Size2.append(Size_2.text)
    except NoSuchElementException:
        Size2.append("--------")
        
    try:
        Size_3=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[3]")
        Size3.append(Size_3.text)
    except NoSuchElementException:
        Size3.append("--------")
        
    try:
        Size_4=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[2]/div[6]/div/div[7]/div[1]/div/div/div[2]/div/div/a[4]")
        Size4.append(Size_4.text)
    except NoSuchElementException:
        Size4.append("--------")
        
    try:
        occasion=driver.find_element(By.XPATH,"/html/body/footer/div[1]/div[3]/div[1]/div/div/ul/li[5]/a")
        Occasion.append(occasion.text)
    except NoSuchElementException:
        Occasion.append("--------")

In [172]:
len(Weartype), len(Materialtype), len(reviews), len(Countryoforigin), len(Returntime), len(color1), len(color2), len(Size1), len(Size2), len(Size3), len(Size4), len(Occasion)

(30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30)

In [173]:
dataq1 = {
    'Wear_type': Weartype,
    'Material_type': Materialtype,
    'Reviews': reviews,
    'color1': color1,
    'color2': color2
     }

In [174]:
dfn5 = pd.DataFrame(dataq1)

In [175]:
dfn5.rename_axis('Sno', inplace=True)

In [177]:
dfn5.to_csv('ListM13.csv', index=True)

In [176]:
dfn5

,Wear_type,Material_type,Reviews,color1,color2
Sno,,,,,
0,Kurta Pajama,,124 people have viewed the product recently,,
1,Kurta Pajama,--------,--------,--------,
2,Kurta Pajama,,674 people have viewed the product recently,,
3,Kurta Pajama,--------,--------,--------,
4,Kurta Pajama,--------,674 people have viewed the product recently,--------,
5,Kurta Pajama,,674 people have viewed the product recently,,
6,Kurta Pajama,--------,--------,--------,
7,Kurta Pajama,--------,--------,--------,
8,Kurta Pajama,,674 people have viewed the product recently,,
9,Kurta Pajama,--------,--------,--------,
10,Kurta Pajama,--------,--------,--------,
11,Kurta Pajama,--------,--------,--------,
12,Kurta Pajama,--------,674 people have viewed the product recently,--------,
13,Kurta Pajama,--------,674 people have viewed the product recently,--------,
14,Kurta Pajama,--------,--------,--------,
15,Kurta Pajama,,674 people have viewed the product recently,,--------
16,Kurta Pajama,,124 people have viewed the product recently,,--------
17,Kurta Pajama,,672 people have viewed the product recently,,--------
18,Kurta Pajama,--------,--------,--------,--------
19,Kurta Pajama,--------,--------,--------,
20,Kurta Pajama,--------,437 people have viewed the product recently,--------,
21,Kurta Pajama,--------,--------,--------,--------
22,Kurta Pajama,,278 people have viewed the product recently,,--------
23,Kurta Pajama,,672 people have viewed the product recently,,
24,Kurta Pajama,,278 people have viewed the product recently,,--------
25,Kurta Pajama,,674 people have viewed the product recently,,--------
26,Kurta Pajama,,124 people have viewed the product recently,,--------
27,Kurta Pajama,,278 people have viewed the product recently,,
28,Kurta Pajama,--------,--------,--------,--------
29,Kurta Pajama,--------,--------,--------,

In [178]:
dataq2= {
    'Country_of_origin':Countryoforigin,
    'Return_time':Returntime,
    'Size1':Size1,
    'Size2':Size2,
    'Size3':Size3,
    'Size4':Size4,
    'Occassion':Occasion
    }

In [179]:
dfn6 = pd.DataFrame(dataq2)

In [180]:
dfn6.rename_axis('Sno', inplace=True)

In [181]:
dfn6['Return_time'] = dfn6['Return_time'].str.replace('[^\d]', '', regex=True)

In [184]:




















dfn6.to_csv('ListM14.csv', index=True)

In [183]:
dfn6

    Country_of_origin Return_time Size1 Size2 Size3 Size4     Occassion
Sno
0               India          15     S     M     L    XL  Indo Western
1            --------                 S     M     L    XL  Indo Western
2               India          15     S     M     L    XL  Indo Western
3            --------                 S     M     L    XL  Indo Western
4               India          15     S     M     L    XL  Indo Western
5               India          15     S     M     L    XL  Indo Western
6            --------                 S     M     L    XL  Indo Western
7            --------                 S     M     L    XL  Indo Western
8               India          15     S     M     L    XL  Indo Western
9            --------                 S     M     L    XL  Indo Western
10           --------                 S     M     L    XL  Indo Western
11           --------                 S     M     L    XL  Indo Western
12              India          15     S     M     L    XL  Indo Western
13              India          15     S     M     L    XL  Indo Western
14           --------                 S     M     L    XL  Indo Western
15              India          15     S     M     L    XL  Indo Western
16              India          15     S     M     L    XL  Indo Western
17              India          15     S     M     L    XL  Indo Western
18           --------                 S     M     L    XL  Indo Western
19           --------                 S     M     L    XL  Indo Western
20              India          15     S     M     L    XL  Indo Western
21           --------                 S     M     L    XL  Indo Western
22              India          15     S     M     L    XL  Indo Western
23              India          15     S     M     L    XL  Indo Western
24              India          15     S     M     L    XL  Indo Western
25              India          15     S     M     L    XL  Indo Western
26              India          15     S     M     L    XL  Indo Western
27              India          15     S     M     L    XL  Indo Western
28           --------                 S     M     L    XL  Indo Western
29           --------                 S     M     L    XL  Indo Western

In [185]:
Manyavar_M1= pd.concat([df, df3,df6, dfn1, dfn4], ignore_index=True)

In [188]:
Manyavar_M1.to_csv('Manyavar_M1.csv', index=True)

In [187]:
Manyavar_M1

,Brand,Category,Product_type,Product_Name,Product_code,Price
0,Vedant Fashions Ltd.,Men,Kurta Pajama,Rust Orange Printed Kurta Set,SOSK630-332,"₹ 3,499"
1,Vedant Fashions Ltd.,Men,Kurta Pajama,Flamingo Pink Chikankari Embroidered Kurta Set,SDES820-325,"₹ 4,999"
2,Vedant Fashions Ltd.,Men,Kurta Pajama,Teal Blue Chikankari Patterned Kurta Set,SDES820-326,"₹ 4,999"
3,Vedant Fashions Ltd.,Men,Kurta Pajama,Lime Green Chikankari Kurta Set,SDES784-334,"₹ 3,999"
4,Vedant Fashions Ltd.,Men,Kurta Pajama,Quartz Pink Mandala Printed Kurta Set,CPOSK666-325,"₹ 4,999"
...,...,...,...,...,...,...
145,Vedant Fashions Ltd.,Men,Kurta Pajama,Golden Jacquard Printed Kurta Set,SDES846-303,"₹ 2,999"
146,Vedant Fashions Ltd.,Men,Kurta Pajama,Antique White Angrakha Style Diamond Printed K...,KL12111-302,"₹ 3,499"
147,Vedant Fashions Ltd.,Men,Kurta Pajama,Soft Blue Medallion Print Kurta Set,CPOSK663-341,"₹ 4,999"
148,Vedant Fashions Ltd.,Men,Kurta Pajama,Ivory Cream Detailed Traditional South Indian ...,SOSK712-302,"₹ 4,999"
149,Vedant Fashions Ltd.,Men,Kurta Pajama,Maroon Self Patterned Kurta Set,SDES993-307,"₹ 2,499"

In [189]:
Manyavar_M2= pd.concat([df1, df4,df7, dfn2, dfn5], ignore_index=True)

In [191]:
Manyavar_M2.to_csv('Manyavar_M2.csv', index=True)

In [190]:
Manyavar_M2

,Wear_type,Material_type,Reviews,color1,color2
0,Kurta Pajama,--------,674 people have viewed the product recently,--------,--------
1,Kurta Pajama,--------,674 people have viewed the product recently,--------,
2,Kurta Pajama,,674 people have viewed the product recently,,
3,Kurta Pajama,,--------,,
4,Kurta Pajama,,674 people have viewed the product recently,,--------
...,...,...,...,...,...
145,Kurta Pajama,,674 people have viewed the product recently,,--------
146,Kurta Pajama,,124 people have viewed the product recently,,--------
147,Kurta Pajama,,278 people have viewed the product recently,,
148,Kurta Pajama,--------,--------,--------,--------
149,Kurta Pajama,--------,--------,--------,

In [192]:
Manyavar_M3= pd.concat([df2, df5,df8, dfn3, dfn6], ignore_index=True)

In [194]:
Manyavar_M3.to_csv('Manyavar_M3.csv', index=True)

In [193]:
Manyavar_M3

    Country_of_origin Return_time Size1 Size2 Size3 Size4     Occassion
0               India          15     S     M     L    XL  Indo Western
1               India          15     S     M     L    XL  Indo Western
2               India          15     S     M     L    XL  Indo Western
3            --------                 S     M     L    XL  Indo Western
4               India          15     S     M     L    XL  Indo Western
..                ...         ...   ...   ...   ...   ...           ...
145             India          15     S     M     L    XL  Indo Western
146             India          15     S     M     L    XL  Indo Western
147             India          15     S     M     L    XL  Indo Western
148          --------                 S     M     L    XL  Indo Western
149          --------                 S     M     L    XL  Indo Western

[150 rows x 7 columns]