In [2]:
#Importing necessary libraries-
import selenium
import pandas as pd
import time
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException, InvalidElementStateException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import os
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
import chromedriver_autoinstaller

import warnings
warnings.filterwarnings('ignore')

In [3]:
driver=webdriver.Chrome()

In [4]:
driver.get('https://www.pantaloons.com/special/yu-brand-store')

In [5]:
#Searching for kid's apparel
search=driver.find_element(By.XPATH,'/html/body/div[1]/main/div/div/section[16]/div/div[3]/div[2]/div/div/a/img')
search.click()

In [ ]:
#Searching for kid's apparel
search1=driver.find_element(By.XPATH,'/html/body/main/div[18]/section[1]/a[1]')
search1.click()

In [8]:
# Fetching product URL first
product_url=[]
start=0
end=1

for page in range(start,end):
    urls=driver.find_elements(By.XPATH,'//div[@class="MuiGrid-root PlpWeb_product-wrapper__3U7s0 MuiGrid-item MuiGrid-grid-xs-4 MuiGrid-grid-md-4 MuiGrid-grid-lg-4"]/div/div/a')
    for url in urls:
        product_url.append(url.get_attribute('href'))
        print("Appended URL:", url.get_attribute('href'))
    print("Finished processing")

Appended URL: https://www.pantaloons.com/p/medium-blue-printed-rayon-shirt-collar-girls-flared-dresses-983163.html
Appended URL: https://www.pantaloons.com/p/white-printed-rayon-round-neck-girls-flared-dresses-983174.html
Appended URL: https://www.pantaloons.com/p/pink-embroidered-cotton-round-neck-girls-flared-dresses-983172.html
Appended URL: https://www.pantaloons.com/p/aqua-printed-cotton-shoulder-straps-girls-flared-dresses-983335.html
Appended URL: https://www.pantaloons.com/p/navy-printed-cotton-satin-round-neck-girls-flared-dresses-981820.html
Appended URL: https://www.pantaloons.com/p/navy-printed-cotton-satin-round-neck-girls-flared-dresses-981816.html
Appended URL: https://www.pantaloons.com/p/yellow-solid-cotton-round-neck-girls-flared-dresses-981817.html
Appended URL: https://www.pantaloons.com/p/white-printed-rayon-round-neck-girls-regular-fit-dresses-981819.html
Appended URL: https://www.pantaloons.com/p/pink-checked-casual-sleeveless-square-neck-baby-flared-dresses-981011.html
Appended URL: https://www.pantaloons.com/p/yellow-solid-rayon-round-neck-girls-flared-dresses-981065.html
Appended URL: https://www.pantaloons.com/p/pink-solid-rayon-square-neck-girls-regular-fit-dresses-981044.html
Appended URL: https://www.pantaloons.com/p/yellow-checked-cotton-shirt-collar-girls-flared-dresses-981047.html
Appended URL: https://www.pantaloons.com/p/medium-blue-printed-rayon-shirt-collar-girls-regular-fit-dresses-981038.html
Appended URL: https://www.pantaloons.com/p/white-solid-cotton-round-neck-girls-flared-dresses-981049.html
Appended URL: https://www.pantaloons.com/p/yellow-solid-rayon-round-neck-girls-flared-dresses-981039.html
Appended URL: https://www.pantaloons.com/p/white-printed-rayon-round-neck-girls-flared-dresses-981066.html
Appended URL: https://www.pantaloons.com/p/green-printed-rayon-square-neck-girls-regular-fit-dresses-981045.html
Appended URL: https://www.pantaloons.com/p/yellow-printed-rayon-shoulder-straps-girls-flared-dresses-981042.html
Appended URL: https://www.pantaloons.com/p/medium-blue-printed-cotton-shoulder-straps-girls-regular-fit-dresses-981041.html
Appended URL: https://www.pantaloons.com/p/red-solid-cotton-round-neck-girls-flared-dresses-981048.html
Appended URL: https://www.pantaloons.com/p/pink-printed-rayon-round-neck-girls-regular-fit-dresses-981043.html
Appended URL: https://www.pantaloons.com/p/yellow-checked-casual-sleeveless-square-neck-baby-flared-dresses-981010.html
Appended URL: https://www.pantaloons.com/p/white-printed-rayon-round-neck-girls-flared-dresses-981040.html
Appended URL: https://www.pantaloons.com/p/white-printed-rayon-square-neck-girls-regular-fit-dresses-981046.html
Appended URL: https://www.pantaloons.com/p/yellow-checked-cotton-shirt-collar-girls-flared-dresses-981067.html
Appended URL: https://www.pantaloons.com/p/pink-print-casual-half-sleeves-round-neck-baby-flared-fit-dresses-976553.html
Appended URL: https://www.pantaloons.com/p/green-solid-cotton-square-neck-girls-flared-fit-dresses-976563.html
Appended URL: https://www.pantaloons.com/p/yellow-print-casual-cap-sleeves-strappy-neck-baby-regular-fit-dresses-975440.html
Appended URL: https://www.pantaloons.com/p/pink-print-casual-sleeveless-strappy-neck-baby-regular-fit-dresses-975439.html
Appended URL: https://www.pantaloons.com/p/medium-blue-solid-cotton-regular-collar-girls-regular-fit-dresses-975437.html
Appended URL: https://www.pantaloons.com/p/medium-blue-print-casual-half-sleeves-round-neck-baby-regular-fit-dresses-975436.html
Appended URL: https://www.pantaloons.com/p/off-white-print-cotton-crew-neck-girls-regular-fit-dresses-975457.html
Appended URL: https://www.pantaloons.com/p/pink-print-cotton-round-neck-girls-regular-fit-dresses-967150.html
Appended URL: https://www.pantaloons.com/p/black-print-cotton-round-neck-girls-regular-fit-dresses-967149.html
Appended URL: https://www.pantaloons.com/p/peach-print-cotton-round-neck-girls-regular-fit-dresses-967151.html
Appended URL: https://www.pantaloons.com/p/coral-print-casual-half-sleeves-crew-neck-baby-comfort-fit-dress-955466.html
Appended URL: https://www.pantaloons.com/p/pink-print-cotton-crew-neck-girls-regular-fit-dresses-965350.html
Appended URL: https://www.pantaloons.com/p/orange-print-casual-half-sleeves-crew-neck-baby-regular-fit-dresses-962024.html
Appended URL: https://www.pantaloons.com/p/medium-blue-cut-sew-cotton-crew-neck-girls-regular-fit-dresses-962029.html
Appended URL: https://www.pantaloons.com/p/yellow-print-casual-cap-sleeves-round-neck-baby-regular-fit-dresses-962025.html
Appended URL: https://www.pantaloons.com/p/medium-blue-solid-cotton-poly-elastane-crew-neck-girls-regular-fit-dresses-962032.html
Appended URL: https://www.pantaloons.com/p/light-blue-solid-cotton-poly-elastane-crew-neck-girls-regular-fit-dresses-962031.html
Appended URL: https://www.pantaloons.com/p/light-blue-cut-sew-cotton-crew-neck-girls-regular-fit-dresses-962030.html
Appended URL: https://www.pantaloons.com/p/navy-print-knee-length-casual-girls-regular-fit-dress-956795.html
Appended URL: https://www.pantaloons.com/p/pink-print-knee-length-casual-girls-regular-fit-dress-956794.html
Appended URL: https://www.pantaloons.com/p/light-blue-solid-knee-length-casual-girls-regular-fit-dress-955477.html
Appended URL: https://www.pantaloons.com/p/lilac-print-casual-sleeveless-crew-neck-baby-comfort-fit-dress-955471.html
Appended URL: https://www.pantaloons.com/p/white-print-casual-sleeveless-crew-neck-baby-comfort-fit-dress-955473.html
Appended URL: https://www.pantaloons.com/p/pink-print-casual-sleeveless-crew-neck-baby-comfort-fit-dress-955472.html
Appended URL: https://www.pantaloons.com/p/medium-blue-solid-knee-length-casual-girls-regular-fit-dress-955478.html
Appended URL: https://www.pantaloons.com/p/navy-print-casual-half-sleeves-crew-neck-baby-comfort-fit-dress-955470.html
Appended URL: https://www.pantaloons.com/p/multi-coloured-print-casual-half-sleeves-crew-neck-baby-regular-fit-dress-948416.html
Appended URL: https://www.pantaloons.com/p/pink-print-casual-cap-sleeves-round-neck-baby-regular-fit-dress-943715.html
Appended URL: https://www.pantaloons.com/p/medium-blue-print-knee-length-casual-girls-regular-fit-dress-943722.html
Appended URL: https://www.pantaloons.com/p/medium-blue-solid-knee-length-casual-girls-regular-fit-dress-943752.html
Appended URL: https://www.pantaloons.com/p/medium-blue-print-knee-length-casual-girls-regular-fit-dress-943721.html
Appended URL: https://www.pantaloons.com/p/medium-blue-print-casual-cap-sleeves-round-neck-baby-regular-fit-dress-943716.html
Appended URL: https://www.pantaloons.com/p/medium-blue-print-casual-half-sleeves-peter-pan-collar-baby-regular-fit-dress-943717.html
Appended URL: https://www.pantaloons.com/p/multi-coloured-print-casual-half-sleeves-crew-neck-baby-regular-fit-dress-943714.html
Appended URL: https://www.pantaloons.com/p/multi-coloured-print-casual-cap-sleeves-crew-neck-baby-regular-fit-dress-943718.html
Appended URL: https://www.pantaloons.com/p/medium-blue-print-knee-length-casual-girls-regular-fit-dress-943724.html
Appended URL: https://www.pantaloons.com/p/medium-blue-solid-knee-length-casual-girls-regular-fit-dress-943753.html
Appended URL: https://www.pantaloons.com/p/multi-coloured-print-casual-half-sleeves-round-neck-baby-regular-fit-dress-941964.html
Appended URL: https://www.pantaloons.com/p/pink-textured-full-length-casual-girls-regular-fit-dress-940921.html
Appended URL: https://www.pantaloons.com/p/navy-solid-casual-full-sleeves-round-neck-baby-regular-fit-dress-940920.html
Appended URL: https://www.pantaloons.com/p/pink-cut-sew-casual-full-sleeves-round-neck-baby-regular-fit-dress-933843.html
Appended URL: https://www.pantaloons.com/p/medium-blue-print-casual-short-sleeves-peter-pan-collar-baby-regular-fit-dress-933838.html
Appended URL: https://www.pantaloons.com/p/multi-coloured-cut-sew-full-length-casual-girls-regular-fit-dress-933831.html
Appended URL: https://www.pantaloons.com/p/medium-blue-print-casual-half-sleeves-round-neck-baby-regular-fit-dress-933841.html
Appended URL: https://www.pantaloons.com/p/off-white-print-casual-half-sleeves-round-neck-baby-regular-fit-dress-933839.html
Appended URL: https://www.pantaloons.com/p/yellow-print-casual-half-sleeves-round-neck-baby-regular-fit-dress-933840.html
Appended URL: https://www.pantaloons.com/p/maroon-self-design-knee-length-casual-girls-regular-fit-dress-933457.html
Appended URL: https://www.pantaloons.com/p/medium-blue-self-design-knee-length-casual-girls-regular-fit-dress-933514.html
Appended URL: https://www.pantaloons.com/p/multi-coloured-cut-sew-full-length-casual-girls-regular-fit-dress-933513.html
Appended URL: https://www.pantaloons.com/p/green-cut-sew-casual-full-sleeves-round-neck-baby-regular-fit-dress-933842.html
Appended URL: https://www.pantaloons.com/p/medium-blue-print-casual-34th-sleeves-peter-pan-collar-baby-regular-fit-dress-933837.html
Appended URL: https://www.pantaloons.com/p/green-cut-sew-casual-full-sleeves-round-neck-baby-regular-fit-dress-915125.html
Appended URL: https://www.pantaloons.com/p/navy-print-casual-full-sleeves-round-neck-baby-regular-fit-dress-924890.html
Appended URL: https://www.pantaloons.com/p/pink-casual-half-sleeves-round-neck-baby-regular-fit-dress-922324.html
Appended URL: https://www.pantaloons.com/p/green-check-knee-length-casual-girls-regular-fit-dress-922366.html
Appended URL: https://www.pantaloons.com/p/pink-full-length-casual-girls-regular-fit-dress-920578.html
Appended URL: https://www.pantaloons.com/p/multi-coloured-knee-length-casual-girls-regular-fit-dress-920579.html
Appended URL: https://www.pantaloons.com/p/medium-blue-casual-sleeveless-round-neck-baby-regular-fit-dress-920575.html
Appended URL: https://www.pantaloons.com/p/navy-casual-sleeveless-baby-regular-fit-dress-919674.html
Appended URL: https://www.pantaloons.com/p/pink-print-casual-sleeveless-strappy-neck-baby-regular-fit-dress-919685.html
Appended URL: https://www.pantaloons.com/p/red-self-design-full-length-casual-girls-regular-fit-dress-919686.html
Appended URL: https://www.pantaloons.com/p/purple-full-length-casual-girls-regular-fit-dress-919683.html
Appended URL: https://www.pantaloons.com/p/medium-blue-full-length-casual-girls-regular-fit-dress-919676.html
Appended URL: https://www.pantaloons.com/p/black-full-length-casual-girls-regular-fit-dress-919678.html
Appended URL: https://www.pantaloons.com/p/navy-full-length-casual-girls-regular-fit-dress-919679.html
Appended URL: https://www.pantaloons.com/p/multi-coloured-knee-length-casual-girls-regular-fit-dress-919680.html
Appended URL: https://www.pantaloons.com/p/red-full-length-casual-girls-regular-fit-dress-919677.html
Appended URL: https://www.pantaloons.com/p/navy-cut-sew-casual-girls-regular-fit-dress-917597.html
Appended URL: https://www.pantaloons.com/p/pink-print-full-length-casual-girls-regular-fit-dress-918442.html
Appended URL: https://www.pantaloons.com/p/yellow-print-casual-full-sleeves-round-neck-baby-regular-fit-dress-916876.html
Appended URL: https://www.pantaloons.com/p/yellow-print-casual-full-sleeves-round-neck-baby-regular-fit-dress-916868.html
Appended URL: https://www.pantaloons.com/p/green-print-casual-sleeveless-baby-regular-fit-dress-916864.html
Appended URL: https://www.pantaloons.com/p/yellow-print-casual-full-sleeves-round-neck-baby-regular-fit-dress-916863.html
Appended URL: https://www.pantaloons.com/p/navy-print-casual-full-sleeves-round-neck-baby-regular-fit-dress-916862.html
Appended URL: https://www.pantaloons.com/p/light-green-print-casual-half-sleeves-baby-regular-fit-dress-916877.html
Appended URL: https://www.pantaloons.com/p/pink-print-casual-half-sleeves-baby-regular-fit-dress-916878.html
Appended URL: https://www.pantaloons.com/p/purple-print-casual-full-sleeves-round-neck-baby-regular-fit-dress-916866.html
Appended URL: https://www.pantaloons.com/p/pink-print-casual-full-sleeves-round-neck-baby-regular-fit-dress-916873.html
Appended URL: https://www.pantaloons.com/p/red-print-casual-full-sleeves-round-neck-baby-regular-fit-dress-916874.html
Appended URL: https://www.pantaloons.com/p/pink-print-casual-full-sleeves-round-neck-baby-regular-fit-dress-916865.html
Appended URL: https://www.pantaloons.com/p/teal-print-casual-full-sleeves-round-neck-baby-regular-fit-dress-916875.html
Finished processing

In [9]:
len(product_url)

106

In [185]:
#Extracting first few records for kids
for url in product_url[0:30]:
    driver.get(url)
    time.sleep(2)
    

Brandname=[]
Category=[]
Producttype=[]
ProductName=[]
Productcode=[]
Price=[]
Weartype=[]
Materialtype=[]
Returntime=[]
reviews=[]
Countryoforigin=[]
reviews=[]
Occasion=[]
color1=[]
color2=[]
Size1=[]
Size2=[]
Size3=[]
Size4=[]

In [202]:
for url in product_url[0:30]:
    driver.get(url)
    time.sleep(2)
    
    
    try:
        Brand_name=driver.find_element(By.XPATH,"/html/body/div[1]/main/section[3]/footer/div[1]/div/div/div[1]/div/div[1]/p")
        Brandname.append(Brand_name.text)
    except NoSuchElementException:
        Brandname.append('--------')
   
    try:
        Cat=driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/div/div/div[2]/div[3]/a/span")
        Category.append(Cat.text)
    except NoSuchElementException:
        Category.append('--------')
        

    try:
        Product_type=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/section/div/div[1]/div[2]/div/div/div/div/ul/li[1]")
        Producttype.append(Product_type.text)
    except NoSuchElementException:
        Producttype.append('--------')
        
    try:
        Product_Name=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[1]/div[3]")
        ProductName.append(Product_Name.text)
    except NoSuchElementException:
        ProductName.append("--------")
        
    try:
        Product_code=driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/div/div/div[1]")
        Productcode.append(Product_code.text)
    except NoSuchElementException:
        Productcode.append("--------")
        
    try:
        Price_u=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[2]/div[2]/s")
        Price.append(Price_u.text)
    except NoSuchElementException:
        Price.append("--------")

In [203]:
len(Brandname), len(Category), len(Producttype), len(ProductName), len(Productcode), len(Price)

(30, 30, 30, 30, 30, 30)

In [204]:
data = {
    'Brand': Brandname,
    'Category': Category,
    'Product_type': Producttype,
    'Product_Name': ProductName,
    'Product_code': Productcode,
    'Price': Price
    }

In [205]:
df = pd.DataFrame(data)

In [208]:
df.rename_axis('Sno',inplace=True)

In [211]:
df

,Brand,Category,Product_type,Product_Name,Product_code,Price
Sno,,,,,,
0,Pantaloons,KIDS,Dresses,Medium Blue Printed Rayon Shirt Collar Girls F...,,₹ 1749
1,Pantaloons,KIDS,Dresses,White Printed Rayon Round Neck Girls Flared Dr...,,--------
2,Pantaloons,KIDS,Dresses,Pink Embroidered Cotton Round Neck Girls Flare...,,₹ 1749
3,Pantaloons,KIDS,Dresses,Aqua Printed Cotton Shoulder Straps Girls Flar...,,₹ 1699
4,Pantaloons,KIDS,Dresses,Navy Printed Cotton Satin Round Neck Girls Fla...,,₹ 1499
5,Pantaloons,KIDS,Dresses,Navy Printed Cotton Satin Round Neck Girls Fla...,,₹ 1749
6,Pantaloons,KIDS,Dresses,Yellow Solid Cotton Round Neck Girls Flared Dr...,,--------
7,Pantaloons,KIDS,Dresses,White Printed Rayon Round Neck Girls Regular F...,,₹ 1649
8,Pantaloons,KIDS,Dresses,Pink Checked Casual Sleeveless Square Neck Bab...,,₹ 1499
9,Pantaloons,KIDS,Dresses,Yellow Solid Rayon Round Neck Girls Flared Dre...,,₹ 1749
10,Pantaloons,KIDS,Dresses,Pink Solid Rayon Square Neck Girls Regular Fit...,,₹ 1749
11,Pantaloons,KIDS,Dresses,Yellow Checked Cotton Shirt Collar Girls Flare...,,₹ 1749
12,Pantaloons,KIDS,Dresses,Medium Blue Printed Rayon Shirt Collar Girls R...,,₹ 1999
13,Pantaloons,KIDS,Dresses,White Solid Cotton Round Neck Girls Flared Dre...,,₹ 1749
14,Pantaloons,KIDS,Dresses,Yellow Solid Rayon Round Neck Girls Flared Dre...,,₹ 1999
15,Pantaloons,KIDS,Dresses,White Printed Rayon Round Neck Girls Flared Dr...,,--------
16,Pantaloons,KIDS,Dresses,Green Printed Rayon Square Neck Girls Regular ...,,₹ 1749
17,Pantaloons,KIDS,Dresses,Yellow Printed Rayon Shoulder Straps Girls Fla...,,₹ 1999
18,Pantaloons,KIDS,Dresses,Medium Blue Printed Cotton Shoulder Straps Gir...,,₹ 1999
19,Pantaloons,KIDS,Dresses,Red Solid Cotton Round Neck Girls Flared Dresses,,₹ 1749
20,Pantaloons,KIDS,Dresses,Pink Printed Rayon Round Neck Girls Regular Fi...,,₹ 1749
21,Pantaloons,KIDS,Dresses,Yellow Checked Casual Sleeveless Square Neck B...,,₹ 1499
22,Pantaloons,KIDS,Dresses,White Printed Rayon Round Neck Girls Flared Dr...,,₹ 1999
23,Pantaloons,KIDS,Dresses,White Printed Rayon Square Neck Girls Regular ...,,₹ 1749
24,Pantaloons,KIDS,Dresses,Yellow Checked Cotton Shirt Collar Girls Flare...,,--------
25,Pantaloons,KIDS,Dresses,Pink Print Casual Half Sleeves Round Neck Baby...,,₹ 999
26,Pantaloons,KIDS,Dresses,Green Solid Cotton Square Neck Girls Flared Fi...,,₹ 1849
27,Pantaloons,KIDS,Dresses,Yellow Print Casual Cap Sleeves Strappy Neck B...,,--------
28,Pantaloons,KIDS,Dresses,Pink Print Casual Sleeveless Strappy Neck Baby...,,--------
29,Pantaloons,KIDS,Dresses,Medium Blue Solid Cotton Regular Collar Girls ...,,--------

In [212]:
df.to_csv('ListKG.csv', index=True)

In [188]:
for url in product_url[0:30]:
    driver.get(url)
    time.sleep(2)
    

    try:
        Wear_type=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/section/div/div[1]/div[2]/div/div/div/div/ul/li[1]")
        Weartype.append(Wear_type.text)
    except NoSuchElementException:
        Weartype.append('--------')
   
    try:
        Material_type=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/section/div/div[1]/div[2]/div/div/div/div/ul/li[7]")
        Materialtype.append(Material_type.text)
    except NoSuchElementException:
        Materialtype.append('--------')
        
    try:
        Reviews=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[1]/a/div/span/div")
        reviews.append(Reviews.text)
    except NoSuchElementException:
        reviews.append('--------')
        
    try:
        Countryof_origin=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[6]/div[2]/button")
        Countryoforigin.append(Countryof_origin.text)
    except NoSuchElementException:
        Countryoforigin.append("--------")
        
    try:
        Return_time=driver.find_element(By.XPATH,"/html/body/div[1]/main/section[3]/footer/div[1]/div/div/div[1]/div/h5")
        Returntime.append(Return_time.text)
    except NoSuchElementException:
        Returntime.append("--------")
        
    try:
        color_1=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/section/div/div[1]/div[2]/div/div/div/div/ul/li[4]")
        color1.append(color_1.text)
    except NoSuchElementException:
        color1.append('--------')
        
    try:
        color_2=driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/div/div/div[1]/a/img")
        color2.append(color_2.text)
    except NoSuchElementException:
        color2.append("--------")
        
        
    try:
        Size_1=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[1]/div/span")
        Size1.append(Size_1.text)
    except NoSuchElementException:
        Size1.append("--------")
   
    try:
        Size_2=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[2]/div/span")
        Size2.append(Size_2.text)
    except NoSuchElementException:
        Size2.append("--------")
        
    try:
        Size_3=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[3]/div/span")
        Size3.append(Size_3.text)
    except NoSuchElementException:
        Size3.append("--------")
        
    try:
        Size_4=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[4]/div/span")
        Size4.append(Size_4.text)
    except NoSuchElementException:
        Size4.append("--------")
        
    try:
        occasion=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[6]/div[2]/button")
        Occasion.append(occasion.text)
    except NoSuchElementException:
        Occasion.append("--------")

In [189]:
len(Weartype), len(Materialtype), len(reviews), len(Countryoforigin), len(Returntime), len(color1), len(color2), len(Size1), len(Size2), len(Size3), len(Size4), len(Occasion)

(30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30)

In [190]:
data1 = {
    'Wear_type': Weartype,
    'Material_type': Materialtype,
    'Reviews': reviews,
    'color1': color1,
    'color2': color2
     }

In [191]:
df1 = pd.DataFrame(data1)

In [194]:
df1.rename_axis('Sno', inplace=True)

In [200]:
df1

    Wear_type Material_type                     Reviews       color1 color2
Sno
0     Dresses         Rayon   Be the first one to rate!  Medium Blue
1     Dresses         Rayon   Be the first one to rate!        White
2     Dresses        Cotton   Be the first one to rate!         Pink
3     Dresses        Cotton   Be the first one to rate!         Aqua
4     Dresses        Cotton   Be the first one to rate!         Navy
5     Dresses        Cotton   Be the first one to rate!         Navy
6     Dresses         Rayon   Be the first one to rate!
7     Dresses         Rayon   Be the first one to rate!
8     Dresses        Cotton   Be the first one to rate!         Pink
9     Dresses         Rayon   Be the first one to rate!       Yellow
10    Dresses         Rayon   Be the first one to rate!
11    Dresses        Cotton                        5.0        Yellow
12    Dresses         Rayon   Be the first one to rate!  Medium Blue
13    Dresses        Cotton   Be the first one to rate!        White
14    Dresses         Rayon                        1.0        Yellow
15    Dresses         Rayon   Be the first one to rate!
16    Dresses         Rayon   Be the first one to rate!        Green
17    Dresses         Rayon   Be the first one to rate!       Yellow
18    Dresses         Rayon   Be the first one to rate!
19    Dresses        Cotton   Be the first one to rate!          Red
20    Dresses         Rayon   Be the first one to rate!
21    Dresses        Cotton   Be the first one to rate!       Yellow
22    Dresses         Rayon   Be the first one to rate!        White
23    Dresses         Rayon   Be the first one to rate!
24    Dresses        Cotton   Be the first one to rate!       Yellow
25    Dresses        Cotton   Be the first one to rate!         Pink
26    Dresses        Cotton   Be the first one to rate!        Green
27    Dresses        Cotton   Be the first one to rate!       Yellow
28    Dresses        Cotton   Be the first one to rate!         Pink
29    Dresses        Cotton   Be the first one to rate!  Medium Blue

In [201]:
df1.to_csv('ListKG1.csv', index=True)

In [59]:
data2= {
    'Country_of_origin':Countryoforigin,
    'Return_time':Returntime,
    'Size1':Size1,
    'Size2':Size2,
    'Size3':Size3,
    'Size4':Size4,
    'Occassion':Occasion
    }

In [60]:
df2 = pd.DataFrame(data2)

In [62]:
df2.rename_axis('Sno', inplace=True)

In [81]:
df2.to_csv('ListKG2.csv', index=True)

In [80]:
df2

,Country_of_origin,Return_time,Size1,Size2,Size3,Size4,Occassion
Sno,,,,,,,
0,India,30,2-3Y,3-4Y,4-5Y,5-6Y,Western wear
1,India,30,8-9Y,9-10Y,11-12Y,13-14Y,Western wear
2,India,30,2-3Y,3-4Y,4-5Y,5-6Y,--------
3,India,30,1-2Y,2-3Y,3-4Y,4-5Y,Western wear
4,India,30,2-3Y,3-4Y,4-5Y,5-6Y,Western wear
5,India,30,8-9Y,9-10Y,11-12Y,13-14Y,Western wear
6,India,30,8-9Y,9-10Y,11-12Y,13-14Y,Western wear
7,India,30,2-3Y,3-4Y,4-5Y,5-6Y,Western wear
8,India,30,6-9 M,9-12 M,12-18 M,18-24 M,Western wear
9,India,30,--------,--------,--------,--------,Western wear
10,India,30,8-9Y,9-10Y,11-12Y,13-14Y,Western wear
11,India,30,8-9Y,9-10Y,11-12Y,13-14Y,Western wear
12,India,30,8-9Y,9-10Y,11-12Y,13-14Y,Western wear
13,India,30,8-9Y,9-10Y,11-12Y,13-14Y,Western wear
14,India,30,8-9Y,9-10Y,11-12Y,13-14Y,Western wear
15,India,30,2-3Y,3-4Y,4-5Y,5-6Y,Western wear
16,India,30,8-9Y,9-10Y,11-12Y,13-14Y,Western wear
17,India,30,8-9Y,9-10Y,11-12Y,13-14Y,Western wear
18,India,30,8-9Y,9-10Y,11-12Y,13-14Y,Western wear
19,India,30,8-9Y,9-10Y,11-12Y,13-14Y,Western wear
20,India,30,8-9Y,9-10Y,11-12Y,13-14Y,Western wear
21,India,30,6-9 M,9-12 M,12-18 M,18-24 M,Western wear
22,India,30,8-9Y,9-10Y,11-12Y,13-14Y,Western wear
23,India,30,8-9Y,9-10Y,11-12Y,13-14Y,Western wear
24,India,30,2-3Y,3-4Y,4-5Y,5-6Y,Western wear
25,India,30,3-6 M,6-9 M,9-12 M,12-18 M,Western wear
26,India,30,1-2Y,2-3Y,3-4Y,5-6Y,Western wear
27,India,30,3-6 M,6-9 M,9-12 M,12-18 M,Western wear
28,India,30,3-6 M,6-9 M,9-12 M,12-18 M,Western wear
29,India,30,2-3Y,3-4Y,4-5Y,5-6Y,Western wear

In [69]:
#Extracting first few records for kids
for url in product_url[30:60]:
    driver.get(url)
    time.sleep(2)
    

Brandname=[]
Category=[]
Producttype=[]
ProductName=[]
Productcode=[]
Price=[]
Weartype=[]
Materialtype=[]
Returntime=[]
reviews=[]
Countryoforigin=[]
reviews=[]
Occasion=[]
color1=[]
color2=[]
Size1=[]
Size2=[]
Size3=[]
Size4=[]

In [70]:
for url in product_url[30:60]:
    driver.get(url)
    time.sleep(2)
    
    
    try:
        Brand_name=driver.find_element(By.XPATH,"/html/body/div[1]/main/section[3]/footer/div[1]/div/div/div[1]/div/div[1]/p")
        Brandname.append(Brand_name.text)
    except NoSuchElementException:
        Brandname.append('--------')
   
    try:
        Cat=driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/div/div/div[2]/div[3]/a/span")
        Category.append(Cat.text)
    except NoSuchElementException:
        Category.append('--------')
        

    try:
        Product_type=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/section/div/div[1]/div[2]/div/div/div/div/ul/li[1]")
        Producttype.append(Product_type.text)
    except NoSuchElementException:
        Producttype.append('--------')
        
    try:
        Product_Name=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[1]/div[3]")
        ProductName.append(Product_Name.text)
    except NoSuchElementException:
        ProductName.append("--------")
        
    try:
        Product_code=driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/div/div/div[1]")
        Productcode.append(Product_code.text)
    except NoSuchElementException:
        Productcode.append("--------")
        
    try:
        Price_u=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[2]/div[2]/s")
        Price.append(Price_u.text)
    except NoSuchElementException:
        Price.append("--------")

In [71]:
len(Brandname), len(Category), len(Producttype), len(ProductName), len(Productcode), len(Price)

(30, 30, 30, 30, 30, 30)

In [72]:
datam= {
    'Brand': Brandname,
    'Category': Category,
    'Product_type': Producttype,
    'Product_Name': ProductName,
    'Product_code': Productcode,
    'Price': Price
    }

In [73]:
df3 = pd.DataFrame(datam)

In [78]:
df3.rename_axis('Sno',inplace=True)

In [83]:
df3.to_csv('ListKG3.csv', index=True)

In [82]:
df3

,Brand,Category,Product_type,Product_Name,Product_code,Price
Sno,,,,,,
0,Pantaloons,KIDS,Dresses,Medium Blue Print Casual Half Sleeves Round Ne...,,₹ 799
1,Pantaloons,KIDS,Dresses,Off White Print Cotton Crew Neck Girls Regular...,,₹ 799
2,Pantaloons,KIDS,Dresses,Pink Print Cotton Round Neck Girls Regular Fit...,,₹ 799
3,Pantaloons,KIDS,Dresses,Black Print Cotton Round Neck Girls Regular Fi...,,₹ 799
4,Pantaloons,KIDS,Dresses,Peach Print Cotton Round Neck Girls Regular Fi...,,₹ 999
5,Pantaloons,KIDS,Dresses,Coral Print Casual Half Sleeves Crew Neck Baby...,,₹ 799
6,Pantaloons,KIDS,Dresses,Pink Print Cotton Crew Neck Girls Regular Fit ...,,₹ 799
7,Pantaloons,KIDS,Dresses,Orange Print Casual Half Sleeves Crew Neck Bab...,,₹ 799
8,Pantaloons,KIDS,Dresses,Medium Blue Cut & Sew Cotton Crew Neck Girls R...,,₹ 799
9,Pantaloons,KIDS,Dresses,Yellow Print Casual Cap Sleeves Round Neck Bab...,,₹ 799
10,Pantaloons,KIDS,Dresses,Medium Blue Solid Cotton Poly Elastane Crew Ne...,,₹ 2249
11,Pantaloons,KIDS,Dresses,Light Blue Solid Cotton Poly Elastane Crew Nec...,,₹ 799
12,Pantaloons,KIDS,Dresses,Light Blue Cut & Sew Cotton Crew Neck Girls Re...,,₹ 799
13,Pantaloons,KIDS,Dresses,Navy Print Knee Length Casual Girls Regular Fi...,,₹ 799
14,Pantaloons,KIDS,Dresses,Pink Print Knee Length Casual Girls Regular Fi...,,₹ 799
15,Pantaloons,KIDS,Dresses,Light Blue Solid Knee Length Casual Girls Regu...,,₹ 799
16,Pantaloons,KIDS,Dresses,Lilac Print Casual Sleeveless Crew Neck Baby C...,,₹ 749
17,Pantaloons,KIDS,Dresses,White Print Casual Sleeveless Crew Neck Baby C...,,₹ 799
18,Pantaloons,KIDS,Dresses,Pink Print Casual Sleeveless Crew Neck Baby Co...,,₹ 799
19,Pantaloons,KIDS,Dresses,Medium Blue Solid Knee Length Casual Girls Reg...,,₹ 799
20,Pantaloons,KIDS,Dresses,Navy Print Casual Half Sleeves Crew Neck Baby ...,,₹ 799
21,Pantaloons,KIDS,Dresses,Multi-coloured Print Casual Half Sleeves Crew ...,,₹ 799
22,Pantaloons,KIDS,Dresses,Pink Print Casual Cap Sleeves Round Neck Baby ...,,₹ 999
23,Pantaloons,KIDS,Dresses,Medium Blue Print Knee Length Casual Girls Reg...,,₹ 799
24,Pantaloons,KIDS,Dresses,Medium Blue Solid Knee Length Casual Girls Reg...,,₹ 799
25,Pantaloons,KIDS,Dresses,Medium Blue Print Knee Length Casual Girls Reg...,,₹ 799
26,Pantaloons,KIDS,Dresses,Medium Blue Print Casual Cap Sleeves Round Nec...,,₹ 799
27,Pantaloons,KIDS,Dresses,Medium Blue Print Casual Half Sleeves Peter Pa...,,₹ 1749
28,Pantaloons,KIDS,Dresses,Multi-coloured Print Casual Half Sleeves Crew ...,,₹ 799
29,Pantaloons,KIDS,Dresses,Multi-coloured Print Casual Cap Sleeves Crew N...,,₹ 799

In [86]:
for url in product_url[30:60]:
    driver.get(url)
    time.sleep(2)
    

    try:
        Wear_type=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/section/div/div[1]/div[2]/div/div/div/div/ul/li[1]")
        Weartype.append(Wear_type.text)
    except NoSuchElementException:
        Weartype.append('--------')
   
    try:
        Material_type=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/section/div/div[1]/div[2]/div/div/div/div/ul/li[7]")
        Materialtype.append(Material_type.text)
    except NoSuchElementException:
        Materialtype.append('--------')
        
    try:
        Reviews=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[1]/a/div/span/div")
        reviews.append(Reviews.text)
    except NoSuchElementException:
        reviews.append('--------')
        
    try:
        Countryof_origin=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[6]/div[2]/button")
        Countryoforigin.append(Countryof_origin.text)
    except NoSuchElementException:
        Countryoforigin.append("--------")
        
    try:
        Return_time=driver.find_element(By.XPATH,"/html/body/div[1]/main/section[3]/footer/div[1]/div/div/div[1]/div/h5")
        Returntime.append(Return_time.text)
    except NoSuchElementException:
        Returntime.append("--------")
        
    try:
        color_1=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/section/div/div[1]/div[2]/div/div/div/div/ul/li[4]")
        color1.append(color_1.text)
    except NoSuchElementException:
        color1.append('--------')
        
    try:
        color_2=driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/div/div/div[1]/a/img")
        color2.append(color_2.text)
    except NoSuchElementException:
        color2.append("--------")
        
        
    try:
        Size_1=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[1]/div/span")
        Size1.append(Size_1.text)
    except NoSuchElementException:
        Size1.append("--------")
   
    try:
        Size_2=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[2]/div/span")
        Size2.append(Size_2.text)
    except NoSuchElementException:
        Size2.append("--------")
        
    try:
        Size_3=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[3]/div/span")
        Size3.append(Size_3.text)
    except NoSuchElementException:
        Size3.append("--------")
        
    try:
        Size_4=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[4]/div/span")
        Size4.append(Size_4.text)
    except NoSuchElementException:
        Size4.append("--------")
        
    try:
        occasion=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[6]/div[2]/button")
        Occasion.append(occasion.text)
    except NoSuchElementException:
        Occasion.append("--------")

In [87]:
len(Weartype), len(Materialtype), len(reviews), len(Countryoforigin), len(Returntime), len(color1), len(color2), len(Size1), len(Size2), len(Size3), len(Size4), len(Occasion)

(30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30)

In [88]:
datam1 = {
    'Wear_type': Weartype,
    'Material_type': Materialtype,
    'Reviews': reviews,
    'color1': color1,
    'color2': color2
     }

In [89]:
df4 = pd.DataFrame(datam1)

In [91]:
df4.rename_axis('Sno', inplace=True)

In [97]:
df4

    Wear_type Material_type                     Reviews          color1 color2
Sno
0     Dresses        Cotton                        5.0      Medium Blue
1     Dresses        Cotton   Be the first one to rate!       Off White
2     Dresses        Cotton   Be the first one to rate!            Pink
3     Dresses        Cotton   Be the first one to rate!           Black
4     Dresses        Cotton   Be the first one to rate!           Peach
5     Dresses        Cotton                        2.0            Coral
6     Dresses        Cotton   Be the first one to rate!            Pink
7     Dresses        Cotton                        5.0           Orange
8     Dresses        Cotton                        4.0      Medium Blue
9     Dresses        Cotton   Be the first one to rate!          Yellow
10    Dresses        Cotton   Be the first one to rate!     Medium Blue
11    Dresses        Cotton   Be the first one to rate!      Light Blue
12    Dresses        Cotton   Be the first one to rate!      Light Blue
13    Dresses        Cotton   Be the first one to rate!            Navy
14    Dresses        Cotton   Be the first one to rate!            Pink
15    Dresses        Cotton   Be the first one to rate!      Light Blue
16    Dresses        Cotton   Be the first one to rate!           Lilac
17    Dresses        Cotton   Be the first one to rate!           White
18    Dresses        Cotton   Be the first one to rate!            Pink
19    Dresses        Cotton                        5.0      Medium Blue
20    Dresses        Cotton   Be the first one to rate!            Navy
21    Dresses        Cotton                        5.0   Multi-coloured
22    Dresses        Cotton   Be the first one to rate!            Pink
23    Dresses        Cotton   Be the first one to rate!     Medium Blue
24    Dresses        Cotton   Be the first one to rate!     Medium Blue
25    Dresses        Cotton                        4.0      Medium Blue
26    Dresses        Cotton   Be the first one to rate!     Medium Blue
27    Dresses        Cotton   Be the first one to rate!     Medium Blue
28    Dresses        Cotton   Be the first one to rate!  Multi-coloured
29    Dresses        Cotton   Be the first one to rate!  Multi-coloured

In [98]:
df4.to_csv('ListKG4.csv', index=True)

In [100]:
datam2= {
    'Country_of_origin':Countryoforigin,
    'Return_time':Returntime,
    'Size1':Size1,
    'Size2':Size2,
    'Size3':Size3,
    'Size4':Size4,
    'Occassion':Occasion
    }

In [101]:
df5 = pd.DataFrame(datam2)

In [103]:
df5.rename_axis('Sno', inplace=True)

In [109]:
df5.to_csv('ListKG5.csv', index=True)

In [108]:
df5

    Country_of_origin Return_time  Size1  Size2   Size3    Size4     Occassion
Sno
0               India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
1               India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
2               India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
3               India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
4               India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
5               India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
6               India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
7               India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
8               India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
9               India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
10              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
11              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
12              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
13              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
14              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
15              India          30   8-9Y  9-10Y  11-12Y   13-14Y  Western wear
16              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
17              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
18              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
19              India          30   8-9Y  9-10Y  11-12Y   13-14Y  Western wear
20              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
21              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
22              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
23              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
24              India          30   8-9Y  9-10Y  11-12Y   13-14Y  Western wear
25              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
26              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
27              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
28              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
29              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear

In [110]:
#Extracting first few records for kids
for url in product_url[60:100]:
    driver.get(url)
    time.sleep(2)
    

Brandname=[]
Category=[]
Producttype=[]
ProductName=[]
Productcode=[]
Price=[]
Weartype=[]
Materialtype=[]
Returntime=[]
reviews=[]
Countryoforigin=[]
reviews=[]
Occasion=[]
color1=[]
color2=[]
Size1=[]
Size2=[]
Size3=[]
Size4=[]

In [111]:
for url in product_url[60:100]:
    driver.get(url)
    time.sleep(2)
    
    
    try:
        Brand_name=driver.find_element(By.XPATH,"/html/body/div[1]/main/section[3]/footer/div[1]/div/div/div[1]/div/div[1]/p")
        Brandname.append(Brand_name.text)
    except NoSuchElementException:
        Brandname.append('--------')
   
    try:
        Cat=driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/div/div/div[2]/div[3]/a/span")
        Category.append(Cat.text)
    except NoSuchElementException:
        Category.append('--------')
        

    try:
        Product_type=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/section/div/div[1]/div[2]/div/div/div/div/ul/li[1]")
        Producttype.append(Product_type.text)
    except NoSuchElementException:
        Producttype.append('--------')
        
    try:
        Product_Name=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[1]/div[3]")
        ProductName.append(Product_Name.text)
    except NoSuchElementException:
        ProductName.append("--------")
        
    try:
        Product_code=driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/div/div/div[1]")
        Productcode.append(Product_code.text)
    except NoSuchElementException:
        Productcode.append("--------")
        
    try:
        Price_u=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[2]/div[2]/s")
        Price.append(Price_u.text)
    except NoSuchElementException:
        Price.append("--------")

In [112]:
len(Brandname), len(Category), len(Producttype), len(ProductName), len(Productcode), len(Price)

(40, 40, 40, 40, 40, 40)

In [113]:
datan = {
    'Brand': Brandname,
    'Category': Category,
    'Product_type': Producttype,
    'Product_Name': ProductName,
    'Product_code': Productcode,
    'Price': Price
    }

In [114]:
df6 = pd.DataFrame(datan)

In [116]:
df6.rename_axis('Sno',inplace=True)

In [121]:
df6

,Brand,Category,Product_type,Product_Name,Product_code,Price
Sno,,,,,,
0,Pantaloons,KIDS,Dresses,Medium Blue Print Knee Length Casual Girls Reg...,,₹ 1299
1,Pantaloons,KIDS,Dresses,Medium Blue Solid Knee Length Casual Girls Reg...,,₹ 1299
2,Pantaloons,KIDS,Dresses,Multi-coloured Print Casual Half Sleeves Round...,,₹ 1299
3,Pantaloons,KIDS,Dresses,Pink Textured Full Length Casual Girls Regular...,,₹ 1299
4,Pantaloons,KIDS,Dresses,Navy Solid Casual Full Sleeves Round Neck Baby...,,₹ 1299
5,Pantaloons,KIDS,Dresses,Pink Cut & Sew Casual Full Sleeves Round Neck ...,,₹ 1299
6,Pantaloons,KIDS,Dresses,Medium Blue Print Casual Short Sleeves Peter P...,,₹ 1749
7,Pantaloons,KIDS,Dresses,Multi-coloured Cut & Sew Full Length Casual Gi...,,₹ 1299
8,Pantaloons,KIDS,Dresses,Medium Blue Print Casual Half Sleeves Round Ne...,,₹ 1299
9,Pantaloons,KIDS,Dresses,Off White Print Casual Half Sleeves Round Neck...,,₹ 1299
10,Pantaloons,KIDS,Dresses,Yellow Print Casual Half Sleeves Round Neck Ba...,,₹ 1299
11,Pantaloons,KIDS,Dresses,Maroon Self Design Knee Length Casual Girls Re...,,₹ 1299
12,Pantaloons,KIDS,Dresses,Medium Blue Self Design Knee Length Casual Gir...,,₹ 1299
13,Pantaloons,KIDS,Dresses,Multi-coloured Cut & Sew Full Length Casual Gi...,,₹ 1299
14,Pantaloons,KIDS,Dresses,Green Cut & Sew Casual Full Sleeves Round Neck...,,₹ 999
15,Pantaloons,KIDS,Dresses,Medium Blue Print Casual 3/4th Sleeves Peter P...,,₹ 1299
16,Pantaloons,KIDS,Dresses,Green Cut & Sew Casual Full Sleeves Round Neck...,,₹ 1299
17,Pantaloons,KIDS,Dresses,Navy Print Casual Full Sleeves Round Neck Baby...,,₹ 1299
18,Pantaloons,KIDS,Dresses,Pink Casual Half Sleeves Round Neck Baby Regul...,,₹ 1299
19,Pantaloons,KIDS,Dresses,Green Check Knee Length Casual Girls Regular F...,,₹ 1299
20,Pantaloons,KIDS,Dresses,Pink Full Length Casual Girls Regular Fit Dress,,₹ 1299
21,Pantaloons,KIDS,Dresses,Multi-coloured Knee Length Casual Girls Regula...,,₹ 1299
22,Pantaloons,KIDS,Dresses,Medium Blue Casual Sleeveless Round Neck Baby ...,,₹ 1249
23,Pantaloons,KIDS,Dresses,Navy Casual Sleeveless Baby Regular Fit Dress,,₹ 1299
24,Pantaloons,KIDS,Dresses,Pink Print Casual Sleeveless Strappy Neck Baby...,,₹ 1499
25,Pantaloons,KIDS,Dresses,Red Self Design Full Length Casual Girls Regul...,,₹ 1299
26,Pantaloons,KIDS,Dresses,Purple Full Length Casual Girls Regular Fit Dress,,₹ 1299
27,Pantaloons,KIDS,Dresses,Medium Blue Full Length Casual Girls Regular F...,,₹ 1299
28,Pantaloons,KIDS,Dresses,Black Full Length Casual Girls Regular Fit Dress,,₹ 1299
29,Pantaloons,KIDS,Dresses,Navy Full Length Casual Girls Regular Fit Dress,,₹ 1299
30,Pantaloons,KIDS,Dresses,Multi-coloured Knee Length Casual Girls Regula...,,₹ 1299
31,Pantaloons,KIDS,Dresses,Red Full Length Casual Girls Regular Fit Dress,,₹ 1299
32,Pantaloons,KIDS,Dresses,Navy Cut & Sew CASUAL Girls Regular Fit Dress,,₹ 1499
33,Pantaloons,KIDS,Dresses,Pink Print Full Length Casual Girls Regular Fi...,,₹ 1499
34,Pantaloons,KIDS,Dresses,Yellow Print Casual Full Sleeves Round Neck Ba...,,₹ 1249
35,Pantaloons,KIDS,Dresses,Yellow Print Casual Full Sleeves Round Neck Ba...,,₹ 1299
36,Pantaloons,KIDS,Dresses,Green Print Casual Sleeveless Baby Regular Fit...,,₹ 1299
37,Pantaloons,KIDS,Dresses,Yellow Print Casual Full Sleeves Round Neck Ba...,,₹ 1299
38,Pantaloons,KIDS,Dresses,Navy Print Casual Full Sleeves Round Neck Baby...,,₹ 1249
39,Pantaloons,KIDS,Dresses,Light Green Print Casual Half Sleeves Baby Reg...,,₹ 1299

In [122]:
df6.to_csv('ListKG6.csv', index=True)

In [123]:
for url in product_url[60:100]:
    driver.get(url)
    time.sleep(2)
    

    try:
        Wear_type=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/section/div/div[1]/div[2]/div/div/div/div/ul/li[1]")
        Weartype.append(Wear_type.text)
    except NoSuchElementException:
        Weartype.append('--------')
   
    try:
        Material_type=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/section/div/div[1]/div[2]/div/div/div/div/ul/li[7]")
        Materialtype.append(Material_type.text)
    except NoSuchElementException:
        Materialtype.append('--------')
        
    try:
        Reviews=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[1]/a/div/span/div")
        reviews.append(Reviews.text)
    except NoSuchElementException:
        reviews.append('--------')
        
    try:
        Countryof_origin=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[6]/div[2]/button")
        Countryoforigin.append(Countryof_origin.text)
    except NoSuchElementException:
        Countryoforigin.append("--------")
        
    try:
        Return_time=driver.find_element(By.XPATH,"/html/body/div[1]/main/section[3]/footer/div[1]/div/div/div[1]/div/h5")
        Returntime.append(Return_time.text)
    except NoSuchElementException:
        Returntime.append("--------")
        
    try:
        color_1=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/section/div/div[1]/div[2]/div/div/div/div/ul/li[4]")
        color1.append(color_1.text)
    except NoSuchElementException:
        color1.append('--------')
        
    try:
        color_2=driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/div/div/div[1]/a/img")
        color2.append(color_2.text)
    except NoSuchElementException:
        color2.append("--------")
        
        
    try:
        Size_1=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[1]/div/span")
        Size1.append(Size_1.text)
    except NoSuchElementException:
        Size1.append("--------")
   
    try:
        Size_2=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[2]/div/span")
        Size2.append(Size_2.text)
    except NoSuchElementException:
        Size2.append("--------")
        
    try:
        Size_3=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[3]/div/span")
        Size3.append(Size_3.text)
    except NoSuchElementException:
        Size3.append("--------")
        
    try:
        Size_4=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[4]/div/span")
        Size4.append(Size_4.text)
    except NoSuchElementException:
        Size4.append("--------")
        
    try:
        occasion=driver.find_element(By.XPATH,"/html/body/div[1]/main/div[2]/div/div[2]/div[6]/div[2]/button")
        Occasion.append(occasion.text)
    except NoSuchElementException:
        Occasion.append("--------")

In [126]:
len(Weartype), len(Materialtype), len(reviews), len(Countryoforigin), len(Returntime), len(color1), len(color2), len(Size1), len(Size2), len(Size3), len(Size4), len(Occasion)

(40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40)

In [127]:
datan1 = {
    'Wear_type': Weartype,
    'Material_type': Materialtype,
    'Reviews': reviews,
    'color1': color1,
    'color2': color2
     }

In [128]:
df7 = pd.DataFrame(datan1)

In [130]:
df7.rename_axis('Sno', inplace=True)

In [156]:
df7

    Wear_type Material_type                     Reviews          color1 color2
Sno
0     Dresses        Cotton                        5.0      Medium Blue
1     Dresses        Cotton                        4.0      Medium Blue
2     Dresses        Cotton   Be the first one to rate!  Multi-coloured
3     Dresses        Cotton   Be the first one to rate!            Pink
4     Dresses        Cotton                        3.5             Navy
5     Dresses        Cotton   Be the first one to rate!            Pink
6     Dresses        Cotton   Be the first one to rate!     Medium Blue
7     Dresses        Cotton   Be the first one to rate!  Multi-coloured
8     Dresses        Cotton   Be the first one to rate!     Medium Blue
9     Dresses        Cotton   Be the first one to rate!       Off White
10    Dresses        Cotton   Be the first one to rate!          Yellow
11    Dresses        Cotton                        5.0           Maroon
12    Dresses        Cotton   Be the first one to rate!     Medium Blue
13    Dresses        Cotton                        5.0   Multi-coloured
14    Dresses        Cotton   Be the first one to rate!           Green
15    Dresses        Cotton   Be the first one to rate!     Medium Blue
16    Dresses        Cotton   Be the first one to rate!           Green
17    Dresses        Cotton   Be the first one to rate!            Navy
18    Dresses         Rayon   Be the first one to rate!
19    Dresses        Cotton   Be the first one to rate!           Green
20    Dresses        Cotton   Be the first one to rate!            Pink
21    Dresses        Cotton                        2.0   Multi-coloured
22    Dresses         Rayon   Be the first one to rate!
23    Dresses        Cotton   Be the first one to rate!            Navy
24    Dresses        Cotton                        2.0             Pink
25    Dresses        Cotton   Be the first one to rate!             Red
26    Dresses        Cotton   Be the first one to rate!          Purple
27    Dresses        Cotton   Be the first one to rate!     Medium Blue
28    Dresses        Cotton                        5.0            Black
29    Dresses        Cotton   Be the first one to rate!            Navy
30    Dresses        Cotton   Be the first one to rate!  Multi-coloured
31    Dresses        Cotton   Be the first one to rate!             Red
32    Dresses        Cotton                        5.0             Navy
33    Dresses        Cotton   Be the first one to rate!            Pink
34    Dresses        Cotton   Be the first one to rate!          Yellow
35    Dresses        Cotton   Be the first one to rate!          Yellow
36    Dresses        Cotton   Be the first one to rate!           Green
37    Dresses        Cotton   Be the first one to rate!          Yellow
38    Dresses        Cotton   Be the first one to rate!            Navy
39    Dresses        Cotton   Be the first one to rate!     Light Green

In [157]:
df7.to_csv('ListKG7.csv', index=True)

In [165]:
datan2= {
    'Country_of_origin':Countryoforigin,
    'Return_time':Returntime,
    'Size1':Size1,
    'Size2':Size2,
    'Size3':Size3,
    'Size4':Size4,
    'Occassion':Occasion
    }

In [166]:
df8 = pd.DataFrame(datan2)

In [169]:
df8.rename_axis('Sno', inplace=True)

In [173]:
df8

    Country_of_origin Return_time  Size1  Size2   Size3    Size4     Occassion
Sno
0               India          30   8-9Y  9-10Y  11-12Y   13-14Y  Western wear
1               India          30   8-9Y  9-10Y  11-12Y   13-14Y  Western wear
2               India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
3               India          30   8-9Y  9-10Y  11-12Y   13-14Y  Western wear
4               India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
5               India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
6               India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
7               India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
8               India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
9               India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
10              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
11              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
12              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
13              India          30   8-9Y  9-10Y  11-12Y   13-14Y  Western wear
14              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
15              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
16              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
17              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
18              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
19              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
20              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
21              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
22              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
23              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
24              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
25              India          30   8-9Y  9-10Y  11-12Y   13-14Y  Western wear
26              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
27              India          30   8-9Y  9-10Y  11-12Y   13-14Y  Western wear
28              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
29              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
30              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
31              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
32              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
33              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
34              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
35              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
36              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
37              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
38              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
39              India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear

In [174]:
df8.to_csv('ListKG8.csv', index=True)

In [215]:
Kids_1= pd.concat([df,df3,df6], ignore_index=True)

In [216]:
Kids_1

,Brand,Category,Product_type,Product_Name,Product_code,Price
0,Pantaloons,KIDS,Dresses,Medium Blue Printed Rayon Shirt Collar Girls F...,,₹ 1749
1,Pantaloons,KIDS,Dresses,White Printed Rayon Round Neck Girls Flared Dr...,,--------
2,Pantaloons,KIDS,Dresses,Pink Embroidered Cotton Round Neck Girls Flare...,,₹ 1749
3,Pantaloons,KIDS,Dresses,Aqua Printed Cotton Shoulder Straps Girls Flar...,,₹ 1699
4,Pantaloons,KIDS,Dresses,Navy Printed Cotton Satin Round Neck Girls Fla...,,₹ 1499
...,...,...,...,...,...,...
95,Pantaloons,KIDS,Dresses,Yellow Print Casual Full Sleeves Round Neck Ba...,,₹ 1299
96,Pantaloons,KIDS,Dresses,Green Print Casual Sleeveless Baby Regular Fit...,,₹ 1299
97,Pantaloons,KIDS,Dresses,Yellow Print Casual Full Sleeves Round Neck Ba...,,₹ 1299
98,Pantaloons,KIDS,Dresses,Navy Print Casual Full Sleeves Round Neck Baby...,,₹ 1249
99,Pantaloons,KIDS,Dresses,Light Green Print Casual Half Sleeves Baby Reg...,,₹ 1299

In [217]:
Kids_1.to_csv('Kids_1.csv', index=True)

In [218]:
Kids_2= pd.concat([df1,df4,df7], ignore_index=True)

In [219]:
Kids_2

   Wear_type Material_type                     Reviews       color1 color2
0    Dresses         Rayon   Be the first one to rate!  Medium Blue
1    Dresses         Rayon   Be the first one to rate!        White
2    Dresses        Cotton   Be the first one to rate!         Pink
3    Dresses        Cotton   Be the first one to rate!         Aqua
4    Dresses        Cotton   Be the first one to rate!         Navy
..       ...           ...                         ...          ...    ...
95   Dresses        Cotton   Be the first one to rate!       Yellow
96   Dresses        Cotton   Be the first one to rate!        Green
97   Dresses        Cotton   Be the first one to rate!       Yellow
98   Dresses        Cotton   Be the first one to rate!         Navy
99   Dresses        Cotton   Be the first one to rate!  Light Green

[100 rows x 5 columns]

In [220]:
Kids_2.to_csv('Kids_2.csv', index=True)

In [223]:
Kids_3= pd.concat([df2,df5,df8],ignore_index=True)

In [224]:
Kids_3

   Country_of_origin Return_time  Size1  Size2   Size3    Size4     Occassion
0              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
1              India          30   8-9Y  9-10Y  11-12Y   13-14Y  Western wear
2              India          30   2-3Y   3-4Y    4-5Y     5-6Y      --------
3              India          30   1-2Y   2-3Y    3-4Y     4-5Y  Western wear
4              India          30   2-3Y   3-4Y    4-5Y     5-6Y  Western wear
..               ...         ...    ...    ...     ...      ...           ...
95             India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
96             India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
97             India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
98             India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear
99             India          30  3-6 M  6-9 M  9-12 M  12-18 M  Western wear

[100 rows x 7 columns]

In [225]:
Kids_3.to_csv('Kids_3.csv', index=True)